import type { Destination } from "../types";

// Seed content. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const core: Destination[] = [
  {
    slug: "darjeeling",
    featured: true,
    name: "Darjeeling",
    state: "West Bengal",
    tagline: "Queen of the Hills",
    summary:
      "Tea gardens, the UNESCO toy train and sunrise over Kanchenjunga, the world's third-highest peak.",
    tourType: "hills",
    lat: 27.041,
    lng: 88.2663,
    bestTime: {
      months: "Mar – May, Oct – Dec",
      note: "Clear Kanchenjunga views and pleasant days. Avoid peak monsoon (Jul–Aug).",
    },
    bestMonths: [3, 4, 5, 10, 11, 12],
    howToReach:
      "Fly to Bagdogra (IXB) or take a train to New Jalpaiguri (NJP), then a 3–4 hr shared or private cab uphill.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹3,500–6,000", premium: "₹10,000+" },
    facts: [
      { label: "Altitude", value: "2,042 m" },
      { label: "Landscape", value: "Tea hills" },
      { label: "Best time", value: "Mar–May" },
      { label: "Famous for", value: "Toy train" },
    ],
    experiences: [
      { name: "Tiger Hill sunrise", duration: "3 hrs", icon: "sunrise" },
      { name: "Toy train joy ride", duration: "2 hrs", icon: "train" },
      { name: "Tea estate walk", duration: "2 hrs", icon: "leaf" },
    ],
    minDays: 2,
    lastChecked: "2026-09-20",
    days: [
      {
        title: "Arrive and settle in",
        morning: "Reach Bagdogra or NJP and drive up through tea gardens and Kurseong.",
        afternoon: "Check in near the Mall. Rest; the altitude takes a few hours to get used to.",
        evening: "Walk Mall Road and Chowrasta. Momos and tea at Glenary's or Keventer's.",
        stay: "Near Mall Road",
        tip: "Sit on the left side of the cab going up for valley views.",
        stops: [{ name: "Chowrasta", lat: 27.041, lng: 88.2663 }],
      },
      {
        title: "Sunrise and the toy train loop",
        morning: "Leave at 4 am for Tiger Hill sunrise over Kanchenjunga. Stop at Ghoom Monastery and Batasia Loop on the way back.",
        afternoon: "Himalayan Mountaineering Institute and Padmaja Naidu Zoo (red pandas, snow leopards).",
        evening: "Early night; tomorrow is a full day.",
        stay: "Near Mall Road",
        tip: "Book the Tiger Hill cab the evening before. Carry a warm jacket even in May.",
        stops: [
          { name: "Tiger Hill", lat: 26.996, lng: 88.287 },
          { name: "Batasia Loop", lat: 27.013, lng: 88.246 },
          { name: "HMI and Zoo", lat: 27.0583, lng: 88.2558 },
        ],
      },
      {
        title: "Tea, ropeway and toy train",
        morning: "Happy Valley Tea Estate tour and tasting.",
        afternoon: "Darjeeling Ropeway over the Rangeet valley, then the Tibetan Refugee Self-Help Centre.",
        evening: "Toy train joy ride from Darjeeling station (book on IRCTC in advance).",
        stay: "Near Mall Road",
        stops: [
          { name: "Happy Valley Tea Estate", lat: 27.0517, lng: 88.2615 },
          { name: "Ropeway", lat: 27.0588, lng: 88.256 },
          { name: "Darjeeling station", lat: 27.0374, lng: 88.2632 },
        ],
      },
      {
        title: "Day trip to Mirik",
        morning: "Drive 2 hrs to Mirik through Gopaldhara tea gardens.",
        afternoon: "Boat ride on Sumendu Lake and walk the lakeside path.",
        evening: "Return to Darjeeling by sunset.",
        stay: "Near Mall Road",
        stops: [{ name: "Mirik Lake", lat: 26.887, lng: 88.185 }],
      },
      {
        title: "Kalimpong",
        morning: "Drive to Kalimpong (about 2.5 hrs) along the Teesta river.",
        afternoon: "Deolo Hill, Durpin Monastery and a cactus nursery.",
        evening: "Stay in Kalimpong for a quieter night.",
        stay: "Kalimpong",
        stops: [{ name: "Kalimpong", lat: 27.06, lng: 88.47 }],
      },
      {
        title: "Lamahatta and depart",
        morning: "Lamahatta eco park with prayer flags and pine forest.",
        afternoon: "Head down to NJP or Bagdogra for your onward journey.",
        evening: "Departure.",
        stay: "—",
        tip: "Keep 4 hrs for the drive down; traffic near Siliguri can be slow.",
        stops: [{ name: "Lamahatta", lat: 27.067, lng: 88.357 }],
      },
    ],
  },
  {
    slug: "jaisalmer",
    featured: true,
    name: "Jaisalmer",
    state: "Rajasthan",
    tagline: "The Golden City",
    summary: "A living sandstone fort, carved havelis and a night under the stars on the Thar dunes.",
    tourType: "desert",
    lat: 26.9157,
    lng: 70.9083,
    bestTime: {
      months: "Oct – Mar",
      note: "Cool desert nights and clear skies. Summer days cross 45 °C.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Direct trains from Delhi, Jaipur and Jodhpur. Jaisalmer airport has seasonal flights; Jodhpur is 5 hrs by road.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Landscape", value: "Thar desert" },
      { label: "Altitude", value: "225 m" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Golden fort" },
    ],
    experiences: [
      { name: "Camel safari at Sam", duration: "2–3 hrs", icon: "camel" },
      { name: "Living fort walk", duration: "2–3 hrs", icon: "castle" },
      { name: "Desert camp night", duration: "Overnight", icon: "tent" },
    ],
    minDays: 2,
    lastChecked: "2026-09-18",
    days: [
      {
        title: "The living fort",
        morning: "Arrive and check in. Walk into Jaisalmer Fort, one of the few forts where people still live.",
        afternoon: "Jain temples inside the fort and the fort palace museum.",
        evening: "Sunset over the golden walls from Vyas Chhatri.",
        stay: "Inside or near the fort",
        stops: [
          { name: "Jaisalmer Fort", lat: 26.9124, lng: 70.9126 },
          { name: "Vyas Chhatri", lat: 26.917, lng: 70.906 },
        ],
      },
      {
        title: "Havelis and the dunes",
        morning: "Patwon ki Haveli and Nathmal ki Haveli, then Gadisar Lake.",
        afternoon: "Drive 45 km to Sam Sand Dunes.",
        evening: "Camel safari at sunset, folk music and dinner at a desert camp.",
        stay: "Desert camp at Sam",
        tip: "Choose a camp away from the main strip for a quieter night sky.",
        stops: [
          { name: "Patwon ki Haveli", lat: 26.9177, lng: 70.9143 },
          { name: "Gadisar Lake", lat: 26.9053, lng: 70.9235 },
          { name: "Sam Sand Dunes", lat: 26.8317, lng: 70.5164 },
        ],
      },
      {
        title: "Ghost village and Khaba Fort",
        morning: "Kuldhara, the village abandoned overnight in the 1800s.",
        afternoon: "Khaba Fort and its fossil museum, then back to town.",
        evening: "Rooftop dinner facing the lit-up fort.",
        stay: "Near the fort",
        stops: [
          { name: "Kuldhara", lat: 26.8126, lng: 70.7946 },
          { name: "Khaba Fort", lat: 26.8019, lng: 70.6455 },
        ],
      },
      {
        title: "Longewala and Tanot",
        morning: "Drive about 2.5 hrs to the Longewala war memorial (1971).",
        afternoon: "Tanot Mata temple near the border.",
        evening: "Return to Jaisalmer.",
        stay: "Near the fort",
        tip: "Carry ID; there are army checkpoints on this road.",
        stops: [
          { name: "Longewala", lat: 27.5246, lng: 70.1663 },
          { name: "Tanot Mata", lat: 27.7598, lng: 70.2832 },
        ],
      },
      {
        title: "Cenotaphs and old capitals",
        morning: "Bada Bagh royal cenotaphs at sunrise.",
        afternoon: "Amar Sagar and the Jain temples of Lodurva, the old capital.",
        evening: "Shop for mirror-work textiles in the fort lanes.",
        stay: "Near the fort",
        stops: [
          { name: "Bada Bagh", lat: 26.9547, lng: 70.8854 },
          { name: "Lodurva", lat: 26.9846, lng: 70.7955 },
        ],
      },
      {
        title: "Khuri village and depart",
        morning: "Khuri dunes and a mud-hut village visit.",
        afternoon: "Return to Jaisalmer for your train or flight.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Khuri", lat: 26.6136, lng: 70.7036 }],
      },
    ],
  },
  {
    slug: "goa",
    featured: true,
    name: "Goa",
    state: "Goa",
    tagline: "Sun, sand and Susegad",
    summary: "Beach shacks in the north, quiet coves in the south, and Portuguese-era churches in between.",
    tourType: "beach",
    lat: 15.4909,
    lng: 73.8278,
    bestTime: {
      months: "Nov – Feb",
      note: "Dry, sunny and lively. Monsoon (Jun–Sep) is green and quiet, but the sea is closed for swimming.",
    },
    bestMonths: [11, 12, 1, 2],
    howToReach:
      "Fly to Dabolim (GOI) or Mopa (GOX), or take a train to Madgaon or Thivim. Rent a scooter or book cabs locally.",
    budgetPerDay: { budget: "₹2,000–3,000", mid: "₹5,000–8,000", premium: "₹15,000+" },
    facts: [
      { label: "Coastline", value: "105 km" },
      { label: "Landscape", value: "Beaches" },
      { label: "Best time", value: "Nov–Feb" },
      { label: "Famous for", value: "Seafood" },
    ],
    experiences: [
      { name: "Mandovi sunset cruise", duration: "1 hr", icon: "waves" },
      { name: "Old Goa churches", duration: "2–3 hrs", icon: "church" },
      { name: "Dolphin boat trip", duration: "2 hrs", icon: "fish" },
    ],
    minDays: 2,
    lastChecked: "2026-09-25",
    days: [
      {
        title: "North Goa beaches",
        morning: "Arrive and check in around Calangute or Candolim.",
        afternoon: "Baga and Calangute beaches; lunch at a beach shack.",
        evening: "Sunset at Fort Aguada lighthouse.",
        stay: "Candolim / Calangute",
        stops: [
          { name: "Calangute", lat: 15.5439, lng: 73.7553 },
          { name: "Fort Aguada", lat: 15.4925, lng: 73.7735 },
        ],
      },
      {
        title: "Old Goa and Panjim",
        morning: "Basilica of Bom Jesus and Se Cathedral in Old Goa.",
        afternoon: "Walk the Latin Quarter of Fontainhas in Panjim.",
        evening: "Mandovi river sunset cruise.",
        stay: "Candolim / Calangute",
        tip: "Cover shoulders and knees for the churches.",
        stops: [
          { name: "Basilica of Bom Jesus", lat: 15.5009, lng: 73.9116 },
          { name: "Fontainhas", lat: 15.4977, lng: 73.8325 },
        ],
      },
      {
        title: "Anjuna and Vagator",
        morning: "Anjuna flea market (Wednesdays) or a slow café breakfast.",
        afternoon: "Chapora Fort and Vagator cliffs.",
        evening: "Live music at a beach club in Vagator.",
        stay: "Candolim / Calangute",
        stops: [
          { name: "Anjuna", lat: 15.5735, lng: 73.7403 },
          { name: "Chapora Fort", lat: 15.6061, lng: 73.7363 },
        ],
      },
      {
        title: "South Goa",
        morning: "Drive south to Cabo de Rama fort.",
        afternoon: "Palolem beach; kayak in the calm bay.",
        evening: "Stay in a beach hut at Palolem.",
        stay: "Palolem",
        stops: [
          { name: "Cabo de Rama", lat: 15.0889, lng: 73.9208 },
          { name: "Palolem", lat: 15.01, lng: 74.0232 },
        ],
      },
      {
        title: "Butterfly Beach and dolphins",
        morning: "Early boat from Palolem to spot dolphins.",
        afternoon: "Butterfly Beach, reachable only by boat or a forest trail.",
        evening: "Seafood thali in Palolem.",
        stay: "Palolem",
        stops: [{ name: "Butterfly Beach", lat: 15.0262, lng: 73.9969 }],
      },
      {
        title: "Spice farm and depart",
        morning: "Spice plantation tour with a Goan lunch near Ponda.",
        afternoon: "Head to the airport or station.",
        evening: "Departure.",
        stay: "—",
        tip: "Oct–May you can add a jeep trip to Dudhsagar Falls instead.",
        stops: [{ name: "Ponda spice farm", lat: 15.4, lng: 74.0 }],
      },
    ],
  },
];

