import type { Destination } from "../types";

// Seed content. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const east: Destination[] = [
  {
    slug: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    tagline: "Monasteries and mountain lakes",
    summary: "Sikkim's tidy hill capital, a base for Tsomgo Lake, Nathula and old Buddhist monasteries.",
    tourType: "hills",
    lat: 27.3389,
    lng: 88.6065,
    bestTime: {
      months: "Mar – May, Oct – Dec",
      note: "Clear Kanchenjunga views and open high roads. Monsoon (Jun–Sep) brings landslides; snow can shut Nathula in Jan–Feb.",
    },
    bestMonths: [3, 4, 5, 10, 11, 12],
    howToReach:
      "Fly to Bagdogra (IXB) or take a train to New Jalpaiguri (NJP), then 4–5 hrs by shared or private cab along the Teesta. Pakyong airport has limited flights.",
    budgetPerDay: { budget: "₹1,800–3,000", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "1,650 m" },
      { label: "Landscape", value: "Himalayan hills" },
      { label: "Best time", value: "Mar–May" },
      { label: "Famous for", value: "Monasteries" },
    ],
    experiences: [
      { name: "Tsomgo Lake excursion", duration: "Full day", icon: "mountain" },
      { name: "Rumtek Monastery visit", duration: "2–3 hrs", icon: "temple" },
      { name: "Gangtok ropeway ride", duration: "1 hr", icon: "camera" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and MG Marg",
        morning: "Reach Bagdogra or NJP and drive up along the Teesta river via Rangpo.",
        afternoon: "Check in near MG Marg. Hand your ID and photos to a registered agent for tomorrow's Tsomgo permit.",
        evening: "Walk the car-free MG Marg; momos and thukpa in the side lanes.",
        stay: "Near MG Marg",
        tip: "Foreign nationals need a Restricted Area Permit, issued at the Rangpo check post or in advance.",
        stops: [{ name: "MG Marg", lat: 27.3292, lng: 88.6125 }],
      },
      {
        title: "Tsomgo Lake and Nathula",
        morning: "Early start in a permitted shared or reserved cab to Tsomgo (Changu) Lake at about 3,750 m.",
        afternoon: "Continue to Nathula Pass on the China border and Baba Harbhajan Singh Mandir, if your permit covers it.",
        evening: "Back in Gangtok by late afternoon. Rest; the altitude is tiring.",
        stay: "Near MG Marg",
        tip: "Permits go only through registered agents and need a day's notice. Nathula is open to Indian nationals only and is closed on some weekdays (usually Mon and Tue).",
        stops: [
          { name: "Tsomgo Lake", lat: 27.3742, lng: 88.7633 },
          { name: "Nathula Pass", lat: 27.3866, lng: 88.8306 },
        ],
      },
      {
        title: "Monasteries and Tibetan heritage",
        morning: "Rumtek Monastery, seat of the Karmapa lineage, 24 km from town.",
        afternoon: "Do Drul Chorten and the Namgyal Institute of Tibetology next door.",
        evening: "Enchey Monastery at dusk, then dinner in town.",
        stay: "Near MG Marg",
        tip: "Carry ID for Rumtek; there is a security check at the gate.",
        stops: [
          { name: "Rumtek Monastery", lat: 27.2885, lng: 88.561 },
          { name: "Do Drul Chorten", lat: 27.3197, lng: 88.6081 },
          { name: "Enchey Monastery", lat: 27.3357, lng: 88.619 },
        ],
      },
      {
        title: "Viewpoints around town",
        morning: "Sunrise over Kanchenjunga from Tashi Viewpoint, then Ganesh Tok and Hanuman Tok.",
        afternoon: "Banjhakri Falls park, a short drive out of town.",
        evening: "Ropeway ride from Deorali for views over the town at sunset.",
        stay: "Near MG Marg",
        tip: "Book a local taxi for a 'three-point' or 'seven-point' tour; rates are fixed by the taxi union.",
        stops: [
          { name: "Ganesh Tok", lat: 27.3448, lng: 88.6187 },
          { name: "Banjhakri Falls", lat: 27.3546, lng: 88.5859 },
        ],
      },
      {
        title: "Ravangla and Namchi",
        morning: "Drive about 3 hrs to Ravangla and Buddha Park with its large Buddha statue.",
        afternoon: "Continue to Namchi for the Char Dham complex and the Samdruptse hilltop statue.",
        evening: "Drive back to Gangtok, or stay overnight in Ravangla for a quieter night.",
        stay: "Gangtok or Ravangla",
        stops: [
          { name: "Ravangla", lat: 27.3051, lng: 88.3584 },
          { name: "Namchi", lat: 27.1667, lng: 88.3639 },
        ],
      },
      {
        title: "Lal Bazaar and depart",
        morning: "Lal Bazaar for local produce, cheese and Sikkimese tea.",
        afternoon: "Drive down to Bagdogra or NJP for your onward journey.",
        evening: "Departure.",
        stay: "—",
        tip: "Keep 5 hrs for the drive down; landslides on NH10 can cause delays.",
        stops: [{ name: "Lal Bazaar", lat: 27.3314, lng: 88.6146 }],
      },
    ],
  },
  {
    slug: "andaman",
    featured: true,
    name: "Andaman Islands",
    state: "Andaman & Nicobar Islands",
    tagline: "Clear water, quiet islands",
    summary: "White-sand beaches, coral reefs and colonial history spread across Port Blair, Havelock and Neil.",
    tourType: "beach",
    lat: 11.6234,
    lng: 92.7265,
    bestTime: {
      months: "Oct – May",
      note: "Calm seas and good visibility for snorkelling. Monsoon (Jun–Sep) brings rough seas and ferry cancellations.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3, 4, 5],
    howToReach:
      "Fly to Port Blair (Sri Vijaya Puram, IXZ) from Chennai, Kolkata, Delhi or Bengaluru. Ferries connect Port Blair to Havelock and Neil.",
    budgetPerDay: { budget: "₹3,000–4,500", mid: "₹7,000–12,000", premium: "₹20,000+" },
    facts: [
      { label: "Capital", value: "Sri Vijaya Puram" },
      { label: "Landscape", value: "Tropical islands" },
      { label: "Best time", value: "Oct–May" },
      { label: "Famous for", value: "Coral reefs" },
    ],
    experiences: [
      { name: "Snorkelling at Elephant Beach", duration: "Half day", icon: "fish" },
      { name: "Cellular Jail light and sound show", duration: "1 hr", icon: "castle" },
      { name: "Inter-island ferry", duration: "1–2 hrs", icon: "boat" },
    ],
    minDays: 3,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Port Blair and Cellular Jail",
        morning: "Land in Port Blair and check in.",
        afternoon: "Cellular Jail, the colonial prison where freedom fighters were held, and its museum.",
        evening: "Light and sound show at Cellular Jail, then dinner near Aberdeen Bazaar.",
        stay: "Port Blair",
        tip: "Book ferries to Havelock and Neil before you fly; seats sell out in peak season.",
        stops: [{ name: "Cellular Jail", lat: 11.6743, lng: 92.7479 }],
      },
      {
        title: "Ferry to Havelock",
        morning: "Morning ferry to Havelock (Swaraj Dweep), about 1.5–2.5 hrs depending on the boat.",
        afternoon: "Check in and rest by the water.",
        evening: "Sunset at Radhanagar Beach, one of the best-rated beaches in Asia.",
        stay: "Havelock",
        tip: "Reach the jetty an hour early with a printed ticket and photo ID.",
        stops: [{ name: "Radhanagar Beach", lat: 11.9842, lng: 92.952 }],
      },
      {
        title: "Elephant Beach and Kalapathar",
        morning: "Boat to Elephant Beach for snorkelling over shallow coral.",
        afternoon: "Kalapathar Beach on the east coast; quiet and good for a swim.",
        evening: "Seafood dinner near the main market.",
        stay: "Havelock",
        tip: "On a 3-day trip, take the morning ferry back to Port Blair instead and fly out in the afternoon.",
        stops: [
          { name: "Elephant Beach", lat: 12.0636, lng: 92.9497 },
          { name: "Kalapathar Beach", lat: 11.9877, lng: 93.0104 },
        ],
      },
      {
        title: "Neil Island",
        morning: "Short ferry to Neil (Shaheed Dweep), about 1 hr.",
        afternoon: "Cycle to the Natural Bridge rock formation at low tide.",
        evening: "Sunset at Laxmanpur Beach.",
        stay: "Neil",
        tip: "Check tide timings before visiting the Natural Bridge; it is only walkable at low tide.",
        stops: [
          { name: "Natural Bridge", lat: 11.8257, lng: 93.0136 },
          { name: "Laxmanpur Beach", lat: 11.8318, lng: 93.013 },
        ],
      },
      {
        title: "Bharatpur Beach and back to Port Blair",
        morning: "Glass-bottom boat or snorkelling at Bharatpur Beach near the jetty.",
        afternoon: "Ferry back to Port Blair.",
        evening: "Corbyn's Cove beach for a quiet evening.",
        stay: "Port Blair",
        stops: [
          { name: "Bharatpur Beach", lat: 11.8395, lng: 93.0335 },
          { name: "Corbyn's Cove", lat: 11.6447, lng: 92.7466 },
        ],
      },
      {
        title: "Ross Island and depart",
        morning: "Boat to Ross Island (Netaji Subhas Chandra Bose Dweep), the old British headquarters with ruins and deer.",
        afternoon: "Head to the airport for your flight.",
        evening: "Departure.",
        stay: "—",
        tip: "Ross Island is closed on Wednesdays; check before planning this day.",
        stops: [{ name: "Ross Island", lat: 11.6764, lng: 92.7614 }],
      },
    ],
  },
  {
    slug: "kaziranga",
    name: "Kaziranga",
    state: "Assam",
    tagline: "Land of the rhino",
    summary: "Tall grasslands and wetlands holding most of the world's one-horned rhinos, plus elephants and tigers.",
    tourType: "wildlife",
    lat: 26.6667,
    lng: 93.3667,
    bestTime: {
      months: "Nov – Apr",
      note: "The park opens in phases from Oct and shuts for the monsoon around May, when the Brahmaputra floods it.",
    },
    bestMonths: [11, 12, 1, 2, 3, 4],
    howToReach:
      "Fly to Jorhat (about 2 hrs away) or Guwahati (about 5 hrs). Buses and cabs run along NH-715 to Kohora, the main entry point.",
    budgetPerDay: { budget: "₹2,000–3,500", mid: "₹5,000–9,000", premium: "₹15,000+" },
    facts: [
      { label: "UNESCO site", value: "Since 1985" },
      { label: "Landscape", value: "Grassland, wetland" },
      { label: "Best time", value: "Nov–Apr" },
      { label: "Famous for", value: "One-horned rhino" },
    ],
    experiences: [
      { name: "Jeep safari", duration: "2–3 hrs", icon: "binoculars" },
      { name: "Elephant safari", duration: "1 hr", icon: "sunrise" },
      { name: "Tea garden walk", duration: "2 hrs", icon: "leaf" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive in Kohora",
        morning: "Reach Jorhat or Guwahati and drive to Kohora.",
        afternoon: "Check in and visit the Kaziranga National Orchid and Biodiversity Park at Durgapur.",
        evening: "Assamese thali and an early night before the dawn safari.",
        stay: "Kohora",
        tip: "Book jeep safaris through the official Kaziranga portal or your lodge; morning slots fill first.",
        stops: [{ name: "Kohora", lat: 26.6105, lng: 93.411 }],
      },
      {
        title: "Elephant and jeep safari, Central Range",
        morning: "Dawn elephant safari through the tall grass, then a jeep safari in the Central (Kohora) Range.",
        afternoon: "Rest at the lodge through the midday heat.",
        evening: "Walk a nearby village or tea garden road.",
        stay: "Kohora",
        tip: "Elephant safari slots are limited and run only in the early morning; ask your lodge to book a day ahead.",
        stops: [{ name: "Central Range, Kohora", lat: 26.63, lng: 93.4 }],
      },
      {
        title: "Western Range at Bagori",
        morning: "Jeep safari in the Western (Bagori) Range, known for dense rhino and water buffalo sightings.",
        afternoon: "Guided walk through a tea estate near Kohora.",
        evening: "Cultural evening with Bihu dance at one of the lodges.",
        stay: "Kohora",
        stops: [{ name: "Bagori", lat: 26.58, lng: 93.23 }],
      },
      {
        title: "Eastern Range birding",
        morning: "Jeep safari in the Eastern (Agaratoli) Range around the wetlands, best for birds and pelicans.",
        afternoon: "Lunch in Bokakhat and a slow afternoon.",
        evening: "Rest at the lodge.",
        stay: "Kohora",
        tip: "Carry binoculars and wear muted colours; avoid bright red and white.",
        stops: [{ name: "Agaratoli", lat: 26.63, lng: 93.56 }],
      },
      {
        title: "Gibbon sanctuary day trip",
        morning: "Drive about 3 hrs to Hoollongapar Gibbon Sanctuary near Mariani.",
        afternoon: "Guided forest walk to spot hoolock gibbons, India's only ape.",
        evening: "Return to Kohora.",
        stay: "Kohora",
        stops: [{ name: "Hoollongapar Gibbon Sanctuary", lat: 26.67, lng: 94.35 }],
      },
      {
        title: "Burapahar Range and depart",
        morning: "Early jeep safari in the Burapahar Range, on the Guwahati side of the park.",
        afternoon: "Drive on to Guwahati for your onward journey.",
        evening: "Departure.",
        stay: "—",
        tip: "Keep 5 hrs for the drive to Guwahati airport.",
        stops: [{ name: "Burapahar Range", lat: 26.56, lng: 93.07 }],
      },
    ],
  },
  {
    slug: "jim-corbett",
    name: "Jim Corbett",
    state: "Uttarakhand",
    tagline: "Tiger country",
    summary: "India's oldest national park, with sal forests, the Ramganga river and some of the best tiger sightings.",
    tourType: "wildlife",
    lat: 29.3948,
    lng: 79.1265,
    bestTime: {
      months: "Nov – Jun",
      note: "Core zones open mid-Oct to Jun; Dhikala from mid-Nov. Summer is hot but good for tigers. Jhirna stays open year-round.",
    },
    bestMonths: [11, 12, 1, 2, 3, 4, 5, 6],
    howToReach:
      "Direct trains from Delhi to Ramnagar, or a 5–6 hr drive. Pantnagar is the nearest airport, about 2 hrs away.",
    budgetPerDay: { budget: "₹2,000–3,500", mid: "₹6,000–10,000", premium: "₹18,000+" },
    facts: [
      { label: "Established", value: "1936" },
      { label: "Landscape", value: "Sal forest, grassland" },
      { label: "Best time", value: "Nov–Jun" },
      { label: "Famous for", value: "Bengal tiger" },
    ],
    experiences: [
      { name: "Jeep safari", duration: "3–4 hrs", icon: "binoculars" },
      { name: "Night at Dhikala", duration: "Overnight", icon: "tent" },
      { name: "Corbett Museum, Kaladhungi", duration: "1–2 hrs", icon: "castle" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive in Ramnagar",
        morning: "Reach Ramnagar by train or road and check in along the Kosi river.",
        afternoon: "Rest, and collect your safari permits if not done online.",
        evening: "Garjia Devi temple on a rock in the Kosi river.",
        stay: "Ramnagar / Dhikuli",
        tip: "Book safaris only on the official Corbett Tiger Reserve portal; permits open weeks ahead and sell out fast.",
        stops: [{ name: "Garjia Devi Temple", lat: 29.4614, lng: 79.149 }],
      },
      {
        title: "Bijrani safari",
        morning: "Dawn jeep safari in the Bijrani zone, entering at Amdanda gate.",
        afternoon: "Rest at the resort through the heat of the day.",
        evening: "Walk along the Kosi river.",
        stay: "Ramnagar / Dhikuli",
        tip: "Carry the same ID you used to book; it is checked at the gate.",
        stops: [{ name: "Amdanda Gate (Bijrani)", lat: 29.405, lng: 79.13 }],
      },
      {
        title: "Into Dhikala",
        morning: "Enter through Dhangarhi gate and drive deep into the reserve to Dhikala.",
        afternoon: "Afternoon safari or canter ride on the Ramganga grasslands.",
        evening: "Night at the forest rest house; no lights or noise after dark.",
        stay: "Dhikala Forest Lodge",
        tip: "Dhikala stays must be booked on the official portal and open around mid-Nov. Day visitors can use the shared canter.",
        stops: [{ name: "Dhikala", lat: 29.5536, lng: 78.8625 }],
      },
      {
        title: "Dhikala dawn and back",
        morning: "Early safari around Dhikala for elephants, deer and tiger.",
        afternoon: "Drive back to Ramnagar.",
        evening: "Rest at the resort.",
        stay: "Ramnagar / Dhikuli",
        stops: [{ name: "Ramnagar", lat: 29.3948, lng: 79.1265 }],
      },
      {
        title: "Jim Corbett's Kaladhungi",
        morning: "Corbett Museum in Jim Corbett's old winter home at Kaladhungi.",
        afternoon: "Corbett Falls, a short walk through forest.",
        evening: "Return to Ramnagar.",
        stay: "Ramnagar / Dhikuli",
        stops: [{ name: "Kaladhungi", lat: 29.2833, lng: 79.35 }],
      },
      {
        title: "Jhirna safari and depart",
        morning: "Dawn jeep safari in the Jhirna zone, good for elephants and sloth bears.",
        afternoon: "Head back to Delhi or Pantnagar.",
        evening: "Departure.",
        stay: "—",
        tip: "Jhirna and Dhela are the zones to book in the monsoon, when the others are closed.",
        stops: [{ name: "Jhirna Gate", lat: 29.37, lng: 78.99 }],
      },
    ],
  },
  {
    slug: "rishikesh",
    featured: true,
    name: "Rishikesh",
    state: "Uttarakhand",
    tagline: "Yoga, rafting and the Ganga",
    summary: "A riverside town at the foot of the Himalaya known for yoga, white-water rafting and the evening aarti.",
    tourType: "mountain",
    lat: 30.0869,
    lng: 78.2676,
    bestTime: {
      months: "Oct – Apr",
      note: "Pleasant days and rafting open. May–Jun is hot; rafting stops in the monsoon (roughly Jul to mid-Sep).",
    },
    bestMonths: [10, 11, 12, 1, 2, 3, 4],
    howToReach:
      "Fly to Dehradun (Jolly Grant, DED), about 40 min away. Trains run to Rishikesh and Haridwar; Delhi is 6–7 hrs by road.",
    budgetPerDay: { budget: "₹1,200–2,500", mid: "₹3,500–6,000", premium: "₹12,000+" },
    facts: [
      { label: "Landscape", value: "Ganga valley" },
      { label: "Best time", value: "Oct–Apr" },
      { label: "Famous for", value: "Yoga, rafting" },
      { label: "Food", value: "Vegetarian town" },
    ],
    experiences: [
      { name: "White-water rafting", duration: "2–3 hrs", icon: "waves" },
      { name: "Ganga aarti", duration: "1 hr", icon: "temple" },
      { name: "Drop-in yoga class", duration: "1.5 hrs", icon: "sunrise" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and the evening aarti",
        morning: "Reach Rishikesh and check in near Ram Jhula or Tapovan.",
        afternoon: "Walk across Ram Jhula and along the ghats.",
        evening: "Ganga aarti at Parmarth Niketan ghat.",
        stay: "Tapovan / Ram Jhula",
        tip: "Reach the aarti by 5:30 pm in winter for a seat on the steps.",
        stops: [
          { name: "Ram Jhula", lat: 30.1225, lng: 78.3153 },
          { name: "Parmarth Niketan", lat: 30.1196, lng: 78.3134 },
        ],
      },
      {
        title: "Rafting from Shivpuri",
        morning: "Raft the 16 km Shivpuri to Rishikesh stretch, with grade III rapids.",
        afternoon: "Cafés around the Laxman Jhula area and Tapovan.",
        evening: "Aarti at Triveni Ghat, the busiest ghat in town.",
        stay: "Tapovan / Ram Jhula",
        tip: "Book with an operator licensed by the state tourism department and wear the helmet and life jacket throughout.",
        stops: [
          { name: "Shivpuri", lat: 30.14, lng: 78.39 },
          { name: "Triveni Ghat", lat: 30.1036, lng: 78.2969 },
        ],
      },
      {
        title: "Day trip to Haridwar",
        morning: "Drive about 45 min to Haridwar. Ropeway up to Mansa Devi temple.",
        afternoon: "Walk the old bazaars near Har Ki Pauri.",
        evening: "The large Ganga aarti at Har Ki Pauri, then return to Rishikesh.",
        stay: "Tapovan / Ram Jhula",
        tip: "Keep valuables close in the aarti crowd; weekends and festivals are very busy.",
        stops: [
          { name: "Mansa Devi Temple", lat: 29.958, lng: 78.1653 },
          { name: "Har Ki Pauri", lat: 29.9568, lng: 78.1709 },
        ],
      },
      {
        title: "Kunjapuri sunrise and the Beatles Ashram",
        morning: "Pre-dawn drive to Kunjapuri temple for sunrise over the Himalayan peaks.",
        afternoon: "Beatles Ashram (Chaurasi Kutia), the graffiti-covered ashram where the band stayed in 1968.",
        evening: "Drop-in yoga or meditation class at an ashram.",
        stay: "Tapovan / Ram Jhula",
        stops: [
          { name: "Kunjapuri Temple", lat: 30.1977, lng: 78.3306 },
          { name: "Beatles Ashram", lat: 30.1118, lng: 78.3213 },
        ],
      },
      {
        title: "Neelkanth and Neer Garh",
        morning: "Drive up a winding forest road to Neelkanth Mahadev temple.",
        afternoon: "Short hike to Neer Garh waterfall on the way back.",
        evening: "Riverside dinner in Tapovan.",
        stay: "Tapovan / Ram Jhula",
        tip: "Neelkanth gets very crowded during the Kanwar Yatra in Shravan (Jul–Aug); avoid those weeks.",
        stops: [
          { name: "Neelkanth Mahadev", lat: 30.081, lng: 78.344 },
          { name: "Neer Garh Waterfall", lat: 30.135, lng: 78.342 },
        ],
      },
      {
        title: "Morning yoga and depart",
        morning: "Sunrise yoga by the river, then breakfast in town.",
        afternoon: "Head to Dehradun airport or Haridwar station.",
        evening: "Departure.",
        stay: "—",
        tip: "Alcohol and meat are not sold in Rishikesh town; plan accordingly.",
        stops: [{ name: "Triveni Ghat", lat: 30.1036, lng: 78.2969 }],
      },
    ],
  },
];
