import type { Destination } from "../types";

// Seed content. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const extraHeritage: Destination[] = [
  {
    slug: "amritsar",
    featured: true,
    name: "Amritsar",
    state: "Punjab",
    tagline: "City of the Golden Temple",
    summary: "The Golden Temple and its free langar, the Wagah border ceremony and the story of Partition.",
    tourType: "heritage",
    lat: 31.634,
    lng: 74.8723,
    bestTime: {
      months: "Oct – Mar",
      note: "Pleasant days and cold, foggy winter nights. May–Jun regularly crosses 40 °C.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Amritsar (ATQ), or take the Shatabdi or Vande Bharat from Delhi (about 5–6 hrs). The Golden Temple is 15 minutes from the station.",
    budgetPerDay: { budget: "₹1,200–2,000", mid: "₹3,500–6,000", premium: "₹10,000+" },
    facts: [
      { label: "Landscape", value: "Punjab plains" },
      { label: "To Wagah", value: "About 30 km" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Langar" },
    ],
    experiences: [
      { name: "Golden Temple at dawn", duration: "2–3 hrs", icon: "temple" },
      { name: "Attari–Wagah ceremony", duration: "3–4 hrs", icon: "camera" },
      { name: "Old city food walk", duration: "2–3 hrs", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "The Golden Temple",
        morning: "Arrive and check in near the old city. Rest; the temple is busiest from mid-morning.",
        afternoon: "Jallianwala Bagh, the garden of the 1919 massacre, with bullet marks still in the walls.",
        evening: "Golden Temple after dark, then the Palki Sahib ceremony when the holy book is carried to rest for the night.",
        stay: "Near the Golden Temple",
        tip: "Cover your head (scarves are free at the entrance), leave shoes at the free counter and wash your feet before entering.",
        stops: [
          { name: "Golden Temple", lat: 31.62, lng: 74.8765 },
          { name: "Jallianwala Bagh", lat: 31.6207, lng: 74.8801 },
        ],
      },
      {
        title: "Partition Museum and Wagah",
        morning: "Golden Temple at dawn when it is quiet, then eat at the langar and see the community kitchen.",
        afternoon: "Partition Museum in the old Town Hall. Leave by 2:30 pm for Attari, about 45 minutes away.",
        evening: "Beating Retreat ceremony at the Attari–Wagah border, then back for dinner.",
        stay: "Near the Golden Temple",
        tip: "The Partition Museum is usually closed on Mondays. At Wagah carry only ID, phone and wallet; bags are not allowed.",
        stops: [
          { name: "Partition Museum", lat: 31.6264, lng: 74.8768 },
          { name: "Attari–Wagah border", lat: 31.6047, lng: 74.5728 },
        ],
      },
      {
        title: "Fort, temples and bazaars",
        morning: "Gobindgarh Fort, the restored Sikh-era fort with a museum and evening shows.",
        afternoon: "Durgiana Temple, then walk Hall Bazaar and Katra Jaimal Singh for phulkari and juttis.",
        evening: "Amritsari kulcha, lassi and fish in the old city lanes.",
        stay: "Near the Golden Temple",
        stops: [
          { name: "Gobindgarh Fort", lat: 31.6327, lng: 74.864 },
          { name: "Durgiana Temple", lat: 31.6326, lng: 74.8689 },
        ],
      },
      {
        title: "Tarn Taran and Goindwal",
        morning: "Drive about 45 minutes to Tarn Taran Sahib, with one of the largest sarovars of any gurdwara.",
        afternoon: "Continue to Goindwal Sahib and its stepwell of 84 steps on the Beas.",
        evening: "Return to Amritsar for a quiet evening.",
        stay: "Near the Golden Temple",
        stops: [
          { name: "Tarn Taran Sahib", lat: 31.4517, lng: 74.9256 },
          { name: "Goindwal Sahib", lat: 31.371, lng: 75.149 },
        ],
      },
      {
        title: "Harike wetland",
        morning: "Drive about 1.5 hrs to Harike, where the Beas and Sutlej meet.",
        afternoon: "Birdwatching along the barrage; Nov–Feb brings large numbers of migratory ducks.",
        evening: "Back to Amritsar; last walk around the temple sarovar.",
        stay: "Near the Golden Temple",
        tip: "Outside winter, swap this day for Ram Tirath, the ashram linked to the Ramayana, west of the city.",
        stops: [{ name: "Harike wetland", lat: 31.16, lng: 74.95 }],
      },
      {
        title: "Khalsa College and depart",
        morning: "Khalsa College, a 1890s Indo-Saracenic campus on the GT Road.",
        afternoon: "Pick up papad, wadiyan and spices from the old city, then head to the airport or station.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Khalsa College", lat: 31.6366, lng: 74.8255 }],
      },
    ],
  },
  {
    slug: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    tagline: "The Blue City",
    summary: "Mehrangarh Fort above a maze of blue houses, stepwells, and Bishnoi villages at the desert edge.",
    tourType: "heritage",
    lat: 26.2389,
    lng: 73.0243,
    bestTime: {
      months: "Oct – Mar",
      note: "Warm days and cool nights. Apr–Jun is very hot, often above 42 °C.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Jodhpur (JDH) or take a train to Jodhpur Junction; direct trains run from Delhi, Jaipur and Mumbai. Autos are the easiest way round the old city.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹15,000+" },
    facts: [
      { label: "Landscape", value: "Thar edge" },
      { label: "Fort built", value: "1459" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Blue houses" },
    ],
    experiences: [
      { name: "Mehrangarh Fort", duration: "3 hrs", icon: "castle" },
      { name: "Blue city lane walk", duration: "2 hrs", icon: "camera" },
      { name: "Bishnoi village visit", duration: "Half day", icon: "leaf" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Mehrangarh Fort",
        morning: "Arrive and check in around the old city.",
        afternoon: "Mehrangarh Fort and museum; the audio guide is worth taking. Last entry is usually around 5 pm.",
        evening: "Clock Tower and Sardar Market, then dinner on a rooftop facing the lit fort.",
        stay: "Old city, below the fort",
        tip: "Stay in the old city so the fort and blue lanes are a walk away.",
        stops: [
          { name: "Mehrangarh Fort", lat: 26.298, lng: 73.0185 },
          { name: "Clock Tower", lat: 26.295, lng: 73.0244 },
        ],
      },
      {
        title: "Blue lanes and Umaid Bhawan",
        morning: "Jaswant Thada marble cenotaph, then walk down through the blue houses of Brahmpuri.",
        afternoon: "Toorji ka Jhalra stepwell, then the Umaid Bhawan Palace museum.",
        evening: "Makhaniya lassi and mirchi vada near the Clock Tower.",
        stay: "Old city, below the fort",
        stops: [
          { name: "Jaswant Thada", lat: 26.3036, lng: 73.0213 },
          { name: "Toorji ka Jhalra", lat: 26.2934, lng: 73.0219 },
          { name: "Umaid Bhawan Palace", lat: 26.281, lng: 73.047 },
        ],
      },
      {
        title: "Mandore and Kaylana",
        morning: "Rao Jodha Desert Rock Park, a short trail of native plants below the fort.",
        afternoon: "Mandore Gardens, the old Marwar capital, with red sandstone cenotaphs.",
        evening: "Sunset at Kaylana Lake on the west side of town.",
        stay: "Old city, below the fort",
        stops: [
          { name: "Rao Jodha Desert Rock Park", lat: 26.301, lng: 73.015 },
          { name: "Mandore Gardens", lat: 26.353, lng: 73.036 },
          { name: "Kaylana Lake", lat: 26.287, lng: 72.975 },
        ],
      },
      {
        title: "Osian temples and dunes",
        morning: "Drive about 1.5 hrs to Osian, with 8th–11th century Hindu and Jain temples.",
        afternoon: "Sachiya Mata temple on the hill and the Mahavira Jain temple.",
        evening: "Camel ride on the dunes at sunset, or stay at a desert camp.",
        stay: "Osian camp or Jodhpur",
        stops: [{ name: "Osian", lat: 26.7213, lng: 72.9114 }],
      },
      {
        title: "Bishnoi villages",
        morning: "Village safari to Bishnoi hamlets south of town; blackbuck and chinkara are often seen.",
        afternoon: "Khejarli, where villagers died protecting khejri trees in 1730, then potters and dhurrie weavers.",
        evening: "Back in Jodhpur for a quiet evening.",
        stay: "Old city, below the fort",
        tip: "Go early; animals are easiest to spot in the first two hours after sunrise.",
        stops: [{ name: "Khejarli", lat: 26.09, lng: 73.16 }],
      },
      {
        title: "Markets and depart",
        morning: "Sardar Market for bandhej fabric, spices and leather juttis.",
        afternoon: "Head to the airport or station.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Sardar Market", lat: 26.2945, lng: 73.0243 }],
      },
    ],
  },
  {
    slug: "mysuru",
    name: "Mysuru",
    state: "Karnataka",
    tagline: "City of Palaces",
    summary: "The Wadiyar palace lit by thousands of bulbs, Chamundi Hill, and Tipu Sultan's island fort nearby.",
    tourType: "heritage",
    lat: 12.2958,
    lng: 76.6394,
    bestTime: {
      months: "Oct – Feb",
      note: "Mild and dry. Dasara (Sep–Oct) is spectacular but crowded and pricier.",
    },
    bestMonths: [10, 11, 12, 1, 2],
    howToReach:
      "Train or road from Bengaluru (about 3 hrs); Bengaluru (BLR) is the main airport. Mysuru airport has a few domestic flights.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹3,500–6,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "770 m" },
      { label: "Landscape", value: "Deccan plateau" },
      { label: "Best time", value: "Oct–Feb" },
      { label: "Famous for", value: "Dasara" },
    ],
    experiences: [
      { name: "Palace illumination", duration: "1 hr", icon: "castle" },
      { name: "Chamundi Hill steps", duration: "2–3 hrs", icon: "hike" },
      { name: "Devaraja Market walk", duration: "1–2 hrs", icon: "shopping" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Mysore Palace",
        morning: "Arrive and check in near the palace.",
        afternoon: "Mysore Palace: the Durbar Hall, Kalyana Mantapa and the royal portraits.",
        evening: "Palace illumination if it is a Sunday or public holiday, usually about 7–7:45 pm. Otherwise the sound and light show.",
        stay: "Near the palace",
        tip: "Plan your arrival so a Sunday evening falls in your trip. Shoes are left outside the palace.",
        stops: [{ name: "Mysore Palace", lat: 12.3052, lng: 76.6552 }],
      },
      {
        title: "Chamundi Hill and the market",
        morning: "Climb the 1,000 steps to Chamundeshwari Temple, passing the giant Nandi on the way.",
        afternoon: "St Philomena's Church, then Devaraja Market for flowers, incense and Mysore pak.",
        evening: "Masala dosa and filter coffee at an old city tiffin room.",
        stay: "Near the palace",
        tip: "Start the climb by 7 am. You can take an auto up and walk down instead.",
        stops: [
          { name: "Chamundi Hill", lat: 12.2724, lng: 76.6705 },
          { name: "St Philomena's Church", lat: 12.3209, lng: 76.6587 },
          { name: "Devaraja Market", lat: 12.3105, lng: 76.651 },
        ],
      },
      {
        title: "Srirangapatna",
        morning: "Ranganathittu Bird Sanctuary by boat; painted storks and crocodiles on the rocks.",
        afternoon: "Srirangapatna: Ranganathaswamy Temple, Tipu's summer palace Daria Daulat Bagh and the Gumbaz.",
        evening: "Brindavan Gardens at KRS dam, with a musical fountain in the evening.",
        stay: "Near the palace",
        tip: "Birds are best Dec–Jun. Check the Brindavan fountain timings locally.",
        stops: [
          { name: "Ranganathittu", lat: 12.4245, lng: 76.656 },
          { name: "Daria Daulat Bagh", lat: 12.414, lng: 76.693 },
          { name: "Brindavan Gardens", lat: 12.425, lng: 76.575 },
        ],
      },
      {
        title: "Somnathpur and Talakadu",
        morning: "Drive about 1 hr to Somnathpur's 13th-century Hoysala Chennakesava Temple.",
        afternoon: "Talakadu, temples half-buried in sand on the Kaveri.",
        evening: "Return to Mysuru.",
        stay: "Near the palace",
        stops: [
          { name: "Somnathpur", lat: 12.276, lng: 76.881 },
          { name: "Talakadu", lat: 12.18, lng: 77.03 },
        ],
      },
      {
        title: "Art, rail and silk",
        morning: "Jaganmohan Palace art gallery, with Raja Ravi Varma paintings.",
        afternoon: "Rail Museum, then the government silk weaving factory to see Mysore silk on the looms.",
        evening: "Shop for sandalwood, silk and Mysore pak.",
        stay: "Near the palace",
        stops: [
          { name: "Jaganmohan Palace", lat: 12.3064, lng: 76.6489 },
          { name: "Rail Museum", lat: 12.3165, lng: 76.6435 },
        ],
      },
      {
        title: "Karanji Lake and depart",
        morning: "Karanji Lake walk and its walk-through aviary, next to the zoo.",
        afternoon: "Head to Bengaluru or your train.",
        evening: "Departure.",
        stay: "—",
        tip: "Keep 3–4 hrs for the road to Bengaluru airport.",
        stops: [{ name: "Karanji Lake", lat: 12.303, lng: 76.672 }],
      },
    ],
  },
  {
    slug: "khajuraho",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    tagline: "Temples in stone",
    summary: "A thousand-year-old UNESCO temple group, tigers in Panna, and the riverside palaces of Orchha.",
    tourType: "heritage",
    lat: 24.8318,
    lng: 79.9199,
    bestTime: {
      months: "Oct – Mar",
      note: "Cool and dry. Summer crosses 45 °C; Panna's core zone usually closes for the monsoon.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Khajuraho (HJR), or take a train to Khajuraho station. Jhansi, about 4 hrs by road, has far more trains.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹3,500–6,000", premium: "₹12,000+" },
    facts: [
      { label: "Built", value: "950–1050 CE" },
      { label: "UNESCO", value: "Since 1986" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Temple carvings" },
    ],
    experiences: [
      { name: "Western Group temples", duration: "3 hrs", icon: "temple" },
      { name: "Panna jeep safari", duration: "4 hrs", icon: "binoculars" },
      { name: "Light and sound show", duration: "1 hr", icon: "music" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "The Western Group",
        morning: "Arrive and check in; the town is small and walkable.",
        afternoon: "Western Group with a licensed guide: Kandariya Mahadeva, Lakshmana and Vishvanatha temples.",
        evening: "Light and sound show at the Western Group, in English and Hindi.",
        stay: "Khajuraho town",
        tip: "Afternoon light is best for photographs. Hire guides at the gate, not touts on the road.",
        stops: [
          { name: "Kandariya Mahadeva", lat: 24.8523, lng: 79.9196 },
          { name: "Lakshmana Temple", lat: 24.8519, lng: 79.9227 },
        ],
      },
      {
        title: "Eastern and Southern Groups",
        morning: "Matangeshwar Temple, still in daily worship, then cycle to the Jain temples of the Eastern Group.",
        afternoon: "Duladeo and Chaturbhuj temples of the Southern Group.",
        evening: "Walk the Shiv Sagar lake front.",
        stay: "Khajuraho town",
        tip: "Rent a bicycle; the groups are 2–4 km apart on flat roads.",
        stops: [
          { name: "Matangeshwar Temple", lat: 24.8521, lng: 79.9214 },
          { name: "Parsvanath Temple", lat: 24.846, lng: 79.937 },
          { name: "Duladeo Temple", lat: 24.836, lng: 79.924 },
        ],
      },
      {
        title: "Panna and Raneh Falls",
        morning: "Early jeep safari in Panna National Park from Madla gate (tigers, sloth bears, vultures).",
        afternoon: "Raneh Falls, a canyon of pink and grey granite on the Ken river.",
        evening: "Back to Khajuraho.",
        stay: "Khajuraho town",
        tip: "Book safari permits online well ahead. Raneh has water only after the monsoon.",
        stops: [
          { name: "Panna NP (Madla gate)", lat: 24.73, lng: 80.02 },
          { name: "Raneh Falls", lat: 24.888, lng: 79.777 },
        ],
      },
      {
        title: "Drive to Orchha",
        morning: "Drive about 4 hrs to Orchha on the Betwa river.",
        afternoon: "Orchha Fort: Raja Mahal and Jahangir Mahal.",
        evening: "Evening aarti at Ram Raja Temple, where Ram is worshipped as a king.",
        stay: "Orchha",
        stops: [
          { name: "Orchha Fort", lat: 25.3518, lng: 78.64 },
          { name: "Ram Raja Temple", lat: 25.3509, lng: 78.642 },
        ],
      },
      {
        title: "Orchha cenotaphs",
        morning: "Chaturbhuj Temple and Lakshmi Narayan Temple with its painted ceilings.",
        afternoon: "Riverside walk or a short raft on the Betwa.",
        evening: "Sunset over the royal chhatris from the far bank.",
        stay: "Orchha",
        stops: [{ name: "Betwa chhatris", lat: 25.346, lng: 78.643 }],
      },
      {
        title: "Jhansi and depart",
        morning: "Drive 30 minutes to Jhansi Fort, linked to Rani Lakshmibai.",
        afternoon: "Catch your train from Jhansi.",
        evening: "Departure.",
        stay: "—",
        tip: "Jhansi has direct trains to Delhi, Agra and Bhopal.",
        stops: [{ name: "Jhansi Fort", lat: 25.4585, lng: 78.5755 }],
      },
    ],
  },
  {
    slug: "kochi",
    name: "Kochi",
    state: "Kerala",
    tagline: "Queen of the Arabian Sea",
    summary: "Chinese fishing nets, Portuguese and Dutch lanes, the spice trade and Kathakali in Fort Kochi.",
    tourType: "heritage",
    lat: 9.9312,
    lng: 76.2673,
    bestTime: {
      months: "Oct – Mar",
      note: "Dry and less humid. Monsoon (Jun–Sep) brings heavy rain but green, quiet streets.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Kochi (COK), about 1.5 hrs from Fort Kochi, or take a train to Ernakulam Junction. Ferries and autos link Ernakulam to Fort Kochi.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Landscape", value: "Harbour city" },
      { label: "Old trade", value: "Spices" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Fishing nets" },
    ],
    experiences: [
      { name: "Kathakali performance", duration: "2 hrs", icon: "music" },
      { name: "Fort Kochi heritage walk", duration: "2–3 hrs", icon: "church" },
      { name: "Backwater canoe ride", duration: "2–3 hrs", icon: "boat" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Fort Kochi",
        morning: "Arrive and check in at a Fort Kochi homestay.",
        afternoon: "Chinese fishing nets, St Francis Church (Vasco da Gama's first burial place) and Santa Cruz Basilica.",
        evening: "Kathakali show; come early to watch the make-up being applied.",
        stay: "Fort Kochi",
        tip: "Most Kathakali centres let you watch make-up from about an hour before the show.",
        stops: [
          { name: "Chinese fishing nets", lat: 9.9676, lng: 76.2422 },
          { name: "St Francis Church", lat: 9.9659, lng: 76.2397 },
          { name: "Santa Cruz Basilica", lat: 9.9644, lng: 76.2435 },
        ],
      },
      {
        title: "Mattancherry and Jew Town",
        morning: "Mattancherry Palace with its Ramayana murals.",
        afternoon: "Paradesi Synagogue, then the antique and spice shops of Jew Town.",
        evening: "Kalaripayattu demonstration, then seafood back in Fort Kochi.",
        stay: "Fort Kochi",
        tip: "Mattancherry Palace is usually closed on Fridays; the synagogue on Fridays, Saturdays and Jewish holidays.",
        stops: [
          { name: "Mattancherry Palace", lat: 9.958, lng: 76.2595 },
          { name: "Paradesi Synagogue", lat: 9.9573, lng: 76.2596 },
        ],
      },
      {
        title: "Kumbalangi backwaters",
        morning: "Canoe ride through the canals of Kumbalangi village.",
        afternoon: "Watch crab farming and coir making; lunch of karimeen fish.",
        evening: "Sunset walk on Fort Kochi beach.",
        stay: "Fort Kochi",
        stops: [{ name: "Kumbalangi", lat: 9.875, lng: 76.29 }],
      },
      {
        title: "Vypeen and Cherai beach",
        morning: "Ro-ro ferry from Fort Kochi to Vypeen, then drive north.",
        afternoon: "Cherai beach, with backwaters on one side and the sea on the other.",
        evening: "Stay for sunset, then return to Fort Kochi.",
        stay: "Fort Kochi",
        stops: [{ name: "Cherai beach", lat: 10.142, lng: 76.178 }],
      },
      {
        title: "Alappuzha backwaters",
        morning: "Drive about 1.5 hrs to Alappuzha.",
        afternoon: "Shikara or day houseboat ride on Vembanad's canals.",
        evening: "Return to Kochi, or stay overnight on a houseboat.",
        stay: "Fort Kochi or houseboat",
        stops: [{ name: "Alappuzha", lat: 9.4981, lng: 76.3388 }],
      },
      {
        title: "Hill Palace and depart",
        morning: "Hill Palace at Tripunithura, the old Kochi royal residence and museum.",
        afternoon: "Head to the airport or Ernakulam station.",
        evening: "Departure.",
        stay: "—",
        tip: "Hill Palace is usually closed on Mondays.",
        stops: [{ name: "Hill Palace", lat: 9.952, lng: 76.364 }],
      },
    ],
  },
  {
    slug: "madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    tagline: "The Temple City",
    summary: "The towering Meenakshi temple, a Nayak palace, and the island shrine of Rameswaram within reach.",
    tourType: "heritage",
    lat: 9.9252,
    lng: 78.1198,
    bestTime: {
      months: "Oct – Mar",
      note: "Warm but bearable. Apr–Jun is very hot; Oct–Dec brings some rain.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Madurai (IXM) or take a train to Madurai Junction, a short walk from the Meenakshi temple.",
    budgetPerDay: { budget: "₹1,200–2,000", mid: "₹3,000–5,500", premium: "₹10,000+" },
    facts: [
      { label: "Temple towers", value: "14 gopurams" },
      { label: "Landscape", value: "Vaigai plains" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Jasmine" },
    ],
    experiences: [
      { name: "Meenakshi night ceremony", duration: "1 hr", icon: "temple" },
      { name: "Nayak palace show", duration: "1 hr", icon: "castle" },
      { name: "Jigarthanda and idli trail", duration: "2 hrs", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Meenakshi Amman Temple",
        morning: "Arrive and check in near the temple.",
        afternoon: "Meenakshi Amman Temple once it reopens around 4 pm: the gopurams, Hall of a Thousand Pillars and the tank.",
        evening: "Stay for the night ceremony, when Sundareswarar is carried to Meenakshi's shrine, usually around 9 pm.",
        stay: "Near the temple",
        tip: "Phones are not allowed inside; deposit them at the counter. Wear clothes that cover shoulders and knees.",
        stops: [{ name: "Meenakshi Amman Temple", lat: 9.9195, lng: 78.1193 }],
      },
      {
        title: "Nayak palace and Gandhi Museum",
        morning: "Thirumalai Nayakkar Mahal, the 17th-century palace with giant columns.",
        afternoon: "Gandhi Memorial Museum, which holds the cloth he wore when he was shot.",
        evening: "Sound and light show at the palace, then jigarthanda on West Masi Street.",
        stay: "Near the temple",
        stops: [
          { name: "Thirumalai Nayakkar Mahal", lat: 9.915, lng: 78.124 },
          { name: "Gandhi Memorial Museum", lat: 9.93, lng: 78.139 },
        ],
      },
      {
        title: "Hill temples",
        morning: "Thiruparankundram, a rock-cut Murugan temple at the foot of a granite hill.",
        afternoon: "Alagar Koil, the Vishnu temple in the hills 20 km north-east.",
        evening: "Mattuthavani flower market for jasmine by the kilo.",
        stay: "Near the temple",
        stops: [
          { name: "Thiruparankundram", lat: 9.881, lng: 78.072 },
          { name: "Alagar Koil", lat: 10.074, lng: 78.214 },
        ],
      },
      {
        title: "Rameswaram",
        morning: "Drive about 4 hrs (around 170 km) to Rameswaram, crossing the Pamban bridge to the island.",
        afternoon: "Ramanathaswamy Temple and its long pillared corridors.",
        evening: "Quiet evening by the sea.",
        stay: "Rameswaram",
        tip: "Non-Hindus can see the corridors but not the inner sanctum.",
        stops: [
          { name: "Pamban bridge", lat: 9.283, lng: 79.201 },
          { name: "Ramanathaswamy Temple", lat: 9.2881, lng: 79.3174 },
        ],
      },
      {
        title: "Dhanushkodi",
        morning: "Early drive to Dhanushkodi, the town ruined by the 1964 cyclone, and Arichal Munai at the island's tip.",
        afternoon: "APJ Abdul Kalam Memorial, then drive back to Madurai.",
        evening: "Dinner in Madurai.",
        stay: "Near the temple",
        stops: [
          { name: "Dhanushkodi", lat: 9.178, lng: 79.418 },
          { name: "Kalam Memorial", lat: 9.295, lng: 79.251 },
        ],
      },
      {
        title: "Teppakulam and depart",
        morning: "Vandiyur Mariamman Teppakulam, the huge temple tank with an island mandapam.",
        afternoon: "Pudhu Mandapam for tailors and brass, then the airport or station.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Vandiyur Teppakulam", lat: 9.9093, lng: 78.143 }],
      },
    ],
  },
];
