import type { Destination } from "../types";

// Seed content. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const extraCoast: Destination[] = [
  {
    slug: "varkala",
    featured: true,
    name: "Varkala",
    state: "Kerala",
    tagline: "Cliffs above the sea",
    summary: "Red laterite cliffs over a quiet beach, an old Vishnu temple and slow days of yoga and Ayurveda.",
    tourType: "beach",
    lat: 8.7379,
    lng: 76.7163,
    bestTime: {
      months: "Oct – Mar",
      note: "Calm sea and dry, sunny days. The monsoon (Jun–Sep) brings rough water and many cliff cafes close.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Thiruvananthapuram (TRV), about 50 km or 1.5 hrs by cab. Varkala Sivagiri station is on the main Kerala rail line; an autorickshaw to the cliff takes 10 minutes.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Landscape", value: "Laterite cliffs" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Cliff walk" },
      { label: "Nearest airport", value: "Trivandrum" },
    ],
    experiences: [
      { name: "Sunset on North Cliff", duration: "2 hrs", icon: "sunrise" },
      { name: "Papanasam beach swim", duration: "2–3 hrs", icon: "waves" },
      { name: "Janardhana Swamy temple", duration: "1 hr", icon: "temple" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and walk the cliff",
        morning: "Reach Trivandrum or Varkala station and check in near North Cliff.",
        afternoon: "Rest through the midday heat. Lunch at one of the cliff-top cafes.",
        evening: "Walk the cliff path north at sunset and stay for fresh seafood dinner.",
        stay: "North Cliff",
        tip: "The cliff edge has no railing in many places. Carry a torch after dark.",
        stops: [{ name: "North Cliff", lat: 8.7372, lng: 76.7037 }],
      },
      {
        title: "Papanasam beach and the temple",
        morning: "Swim at Papanasam beach below the cliff. Stay between the lifeguard flags.",
        afternoon: "Janardhana Swamy temple, about 2,000 years old by tradition, then Sivagiri Mutt, the samadhi of Sree Narayana Guru.",
        evening: "Book an Ayurvedic massage, then dinner on the cliff.",
        stay: "North Cliff",
        tip: "Currents can be strong even in season. Swim only where lifeguards are on duty.",
        stops: [
          { name: "Papanasam Beach", lat: 8.7339, lng: 76.7055 },
          { name: "Janardhana Swamy Temple", lat: 8.7346, lng: 76.7105 },
          { name: "Sivagiri Mutt", lat: 8.7367, lng: 76.7197 },
        ],
      },
      {
        title: "Kappil and the backwater",
        morning: "Walk or ride north past Black Beach and Odayam to Kappil, where a backwater meets the sea.",
        afternoon: "Kayak or take a country boat on the Kappil backwater.",
        evening: "Sunset from the Kappil bridge, then back to the cliff.",
        stay: "North Cliff",
        stops: [
          { name: "Black Beach", lat: 8.741, lng: 76.701 },
          { name: "Kappil Beach", lat: 8.782, lng: 76.678 },
        ],
      },
      {
        title: "Day trip to Ponmudi",
        morning: "Leave by 6:30 am for Ponmudi, a hill station about 2.5 hrs inland up a road of hairpin bends.",
        afternoon: "Walk the grassy top, tea gardens and the viewpoints over the Western Ghats.",
        evening: "Drive back down before dark.",
        stay: "North Cliff",
        tip: "Mist often rolls in after noon. Go early and carry a light jacket.",
        stops: [{ name: "Ponmudi", lat: 8.7598, lng: 77.1164 }],
      },
      {
        title: "Anjengo Fort and a slow day",
        morning: "Anjengo Fort, an 18th-century English trading post, and the lighthouse next to it.",
        afternoon: "Back to Varkala for a yoga class or time on the beach.",
        evening: "Last sunset on the cliff.",
        stay: "North Cliff",
        stops: [{ name: "Anjengo Fort", lat: 8.66, lng: 76.757 }],
      },
      {
        title: "Trivandrum and depart",
        morning: "Drive to Thiruvananthapuram. See Padmanabhaswamy temple from outside or go in if you are Hindu.",
        afternoon: "Napier Museum, then head to the airport or station.",
        evening: "Departure.",
        stay: "—",
        tip: "Padmanabhaswamy temple entry is for Hindus only, with a strict dress code: mundu for men, saree or long skirt for women.",
        stops: [
          { name: "Padmanabhaswamy Temple", lat: 8.4828, lng: 76.9436 },
          { name: "Napier Museum", lat: 8.509, lng: 76.955 },
        ],
      },
    ],
  },
  {
    slug: "puri",
    name: "Puri",
    state: "Odisha",
    tagline: "Jagannath's seaside town",
    summary: "The Jagannath temple, a long busy beach, and day trips to Konark, Chilika Lake and painters' villages.",
    tourType: "beach",
    lat: 19.8135,
    lng: 85.8312,
    bestTime: {
      months: "Oct – Feb",
      note: "Cool and dry. Summer is humid and hot. Rath Yatra (Jun or Jul) is spectacular but very crowded.",
    },
    bestMonths: [10, 11, 12, 1, 2],
    howToReach:
      "Fly to Bhubaneswar (BBI), about 60 km or 1.5 hrs by road. Puri station has direct trains from Kolkata, Delhi and other major cities.",
    budgetPerDay: { budget: "₹1,200–2,000", mid: "₹3,500–6,000", premium: "₹10,000+" },
    facts: [
      { label: "Landscape", value: "Bay of Bengal" },
      { label: "Best time", value: "Oct–Feb" },
      { label: "Famous for", value: "Jagannath temple" },
      { label: "Nearest airport", value: "Bhubaneswar" },
    ],
    experiences: [
      { name: "Konark Sun Temple", duration: "3 hrs", icon: "temple" },
      { name: "Dolphin boat at Chilika", duration: "2–3 hrs", icon: "boat" },
      { name: "Patachitra village visit", duration: "2 hrs", icon: "shopping" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and the beach",
        morning: "Reach Bhubaneswar or Puri station and check in near the beach.",
        afternoon: "Rest, then walk the Marine Drive promenade.",
        evening: "Puri beach at sunset and the stalls along Swargadwar.",
        stay: "Near the beach",
        tip: "Puri's sea has strong currents. Swim only near lifeguards, and not at all in rough weather.",
        stops: [{ name: "Puri Beach", lat: 19.798, lng: 85.825 }],
      },
      {
        title: "Jagannath temple and Raghurajpur",
        morning: "Jagannath temple early, before the crowds. Only Hindus may enter; others can view it from the rooftop of the Raghunandan Library opposite.",
        afternoon: "Raghurajpur, a heritage crafts village of patachitra painters, about 30 minutes away.",
        evening: "Back to the beach or Grand Road for the evening temple crowd.",
        stay: "Near the beach",
        tip: "Phones, cameras, bags and leather are not allowed inside the temple. Leave them at your hotel.",
        stops: [
          { name: "Jagannath Temple", lat: 19.8048, lng: 85.818 },
          { name: "Raghurajpur", lat: 19.889, lng: 85.879 },
        ],
      },
      {
        title: "Konark Sun Temple",
        morning: "Drive 35 km up the coast road to Konark. See the 13th-century Sun Temple, a UNESCO site, before it gets hot.",
        afternoon: "Chandrabhaga beach nearby, then the ASI museum.",
        evening: "Drive back along the coast at sunset.",
        stay: "Near the beach",
        tip: "Hire a guide at the gate. The carvings make far more sense with someone to explain them.",
        stops: [
          { name: "Konark Sun Temple", lat: 19.8876, lng: 86.0945 },
          { name: "Chandrabhaga Beach", lat: 19.868, lng: 86.107 },
        ],
      },
      {
        title: "Chilika Lake",
        morning: "Leave early for Satapada, about 1.5 hrs, on the edge of Chilika, Asia's largest brackish-water lagoon.",
        afternoon: "Boat out to look for Irrawaddy dolphins and to the sand bar where the lake meets the sea.",
        evening: "Return to Puri.",
        stay: "Near the beach",
        tip: "Take a government-run boat (OTDC) and ask the boatman not to chase the dolphins.",
        stops: [{ name: "Satapada", lat: 19.667, lng: 85.443 }],
      },
      {
        title: "Pipili and Bhubaneswar",
        morning: "Drive towards Bhubaneswar, stopping at Pipili for appliqué work.",
        afternoon: "Dhauli Peace Pagoda, then the Udayagiri and Khandagiri caves.",
        evening: "Stay in Bhubaneswar.",
        stay: "Bhubaneswar",
        stops: [
          { name: "Pipili", lat: 20.115, lng: 85.832 },
          { name: "Dhauli", lat: 20.192, lng: 85.841 },
          { name: "Udayagiri Caves", lat: 20.263, lng: 85.786 },
        ],
      },
      {
        title: "Old temples and depart",
        morning: "Mukteshwar and Rajarani temples in the old town. Lingaraj is for Hindus only; others can view it from a platform outside.",
        afternoon: "Head to Bhubaneswar airport or station.",
        evening: "Departure.",
        stay: "—",
        stops: [
          { name: "Mukteshwar Temple", lat: 20.243, lng: 85.841 },
          { name: "Lingaraj Temple", lat: 20.2382, lng: 85.8338 },
        ],
      },
    ],
  },
  {
    slug: "kumarakom",
    name: "Kumarakom",
    state: "Kerala",
    tagline: "Life on Vembanad Lake",
    summary: "Lakeside villages on Vembanad, a bird sanctuary, and a night on a houseboat through paddy country.",
    tourType: "backwaters",
    lat: 9.617,
    lng: 76.43,
    bestTime: {
      months: "Sep – Mar",
      note: "Pleasant after the monsoon. Migratory birds are around Nov–Feb. Apr–May is hot and humid.",
    },
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    howToReach:
      "Kottayam station is 15 km away. Kochi airport (COK) is about 2.5 hrs by road.",
    budgetPerDay: { budget: "₹2,000–3,500", mid: "₹6,000–10,000", premium: "₹20,000+" },
    facts: [
      { label: "Landscape", value: "Lake and paddies" },
      { label: "Lake", value: "Vembanad" },
      { label: "Best time", value: "Sep–Mar" },
      { label: "Famous for", value: "Houseboats" },
    ],
    experiences: [
      { name: "Houseboat overnight", duration: "22 hrs", icon: "boat" },
      { name: "Bird sanctuary walk", duration: "2 hrs", icon: "binoculars" },
      { name: "Karimeen lunch", duration: "1 hr", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive by the lake",
        morning: "Reach Kottayam or Kochi and drive to Kumarakom.",
        afternoon: "Check in by the lake. Lunch of karimeen (pearl spot) fry and appam.",
        evening: "Sunset cruise on Vembanad by shikara or small motorboat.",
        stay: "Lakeside Kumarakom",
        stops: [{ name: "Kumarakom", lat: 9.617, lng: 76.43 }],
      },
      {
        title: "Birds, then the houseboat",
        morning: "Kumarakom Bird Sanctuary at opening time, when the birds are most active.",
        afternoon: "Board a houseboat around noon and cruise the lake and canals.",
        evening: "Moored for the night; dinner cooked on board.",
        stay: "Houseboat",
        tip: "Houseboats must moor by evening, so most cruising happens 12–5:30 pm. Check the boat has a government licence.",
        stops: [{ name: "Kumarakom Bird Sanctuary", lat: 9.628, lng: 76.422 }],
      },
      {
        title: "Village walk",
        morning: "Leave the houseboat after breakfast.",
        afternoon: "Village walk: coir-making, toddy tapping, and paddy fields that sit below lake level.",
        evening: "Canoe on the narrow canals at dusk.",
        stay: "Lakeside Kumarakom",
        tip: "Ask your stay to arrange the walk with a local guide; it is the best way to see family-run work.",
        stops: [{ name: "Kumarakom village", lat: 9.605, lng: 76.433 }],
      },
      {
        title: "Pathiramanal and Vaikom",
        morning: "Boat to Pathiramanal, a small wooded island in the middle of Vembanad.",
        afternoon: "Drive to Vaikom Mahadeva temple on the eastern shore.",
        evening: "Back to Kumarakom.",
        stay: "Lakeside Kumarakom",
        stops: [
          { name: "Pathiramanal Island", lat: 9.62, lng: 76.387 },
          { name: "Vaikom Mahadeva Temple", lat: 9.7495, lng: 76.393 },
        ],
      },
      {
        title: "Alappuzha beach",
        morning: "Drive about 1 hr to Alappuzha.",
        afternoon: "Alappuzha beach and the old pier, then the town canals.",
        evening: "Return to Kumarakom.",
        stay: "Lakeside Kumarakom",
        stops: [{ name: "Alappuzha Beach", lat: 9.493, lng: 76.317 }],
      },
      {
        title: "Fort Kochi and depart",
        morning: "Drive to Kochi (about 2.5 hrs).",
        afternoon: "Chinese fishing nets and the lanes of Fort Kochi, then the airport.",
        evening: "Departure.",
        stay: "—",
        tip: "Allow at least 1.5 hrs from Fort Kochi to the airport in evening traffic.",
        stops: [
          { name: "Fort Kochi", lat: 9.968, lng: 76.242 },
          { name: "Kochi Airport", lat: 10.152, lng: 76.4019 },
        ],
      },
    ],
  },
  {
    slug: "munroe-island",
    name: "Munroe Island & Kollam",
    state: "Kerala",
    tagline: "Canals by canoe",
    summary: "Paddle narrow canals on Munroe Island, cruise Ashtamudi Lake and take the long boat to Alappuzha.",
    tourType: "backwaters",
    lat: 8.99,
    lng: 76.615,
    bestTime: {
      months: "Oct – Mar",
      note: "Dry, clear mornings for canoeing. Monsoon canals flood and some trips stop.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Kollam Junction is on the main Kerala rail line; Munroe Island is about 25 km by road or a short train hop to Munroturuttu. Trivandrum airport (TRV) is about 70 km.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹3,500–6,000", premium: "₹9,000+" },
    facts: [
      { label: "Landscape", value: "Canals and lake" },
      { label: "Lake", value: "Ashtamudi" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Canoe rides" },
    ],
    experiences: [
      { name: "Dawn canoe on the canals", duration: "3 hrs", icon: "boat" },
      { name: "Kollam–Alappuzha boat", duration: "8 hrs", icon: "waves" },
      { name: "Ashtamudi seafood", duration: "1 hr", icon: "fish" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive on the island",
        morning: "Reach Kollam and drive or take the train to Munroe Island.",
        afternoon: "Check in at a homestay and walk the village paths.",
        evening: "Sunset over the water; homestay dinner of local fish and tapioca.",
        stay: "Homestay on Munroe Island",
        tip: "Stays are small homestays, not hotels. Book ahead in Dec–Jan.",
        stops: [{ name: "Munroe Island", lat: 8.99, lng: 76.615 }],
      },
      {
        title: "Canoe through the canals",
        morning: "Canoe at 6:30 am through narrow canals under coconut palms, past coir-making and shrimp farms.",
        afternoon: "Rest, then walk to see coir spinning or crab and fish farms.",
        evening: "Country boat out on Ashtamudi at sunset.",
        stay: "Homestay on Munroe Island",
        tip: "Go at dawn. Birds are out, the light is soft, and it gets hot by 10 am.",
        stops: [{ name: "Munroe Island canals", lat: 8.995, lng: 76.62 }],
      },
      {
        title: "Kollam town and the lake",
        morning: "Drive to Kollam. Thangasseri lighthouse and the old Portuguese-Dutch fort ruins.",
        afternoon: "Ashtamudi Lake cruise from the Kollam boat jetty.",
        evening: "Kollam beach at sunset.",
        stay: "Kollam",
        stops: [
          { name: "Thangasseri Lighthouse", lat: 8.881, lng: 76.568 },
          { name: "Kollam Boat Jetty", lat: 8.887, lng: 76.593 },
          { name: "Kollam Beach", lat: 8.877, lng: 76.588 },
        ],
      },
      {
        title: "Sasthamkotta and Jatayu",
        morning: "Sasthamkotta, Kerala's largest freshwater lake.",
        afternoon: "Jatayu Earth's Center, a huge bird sculpture on a rock hill, reached by cable car.",
        evening: "Back to Kollam.",
        stay: "Kollam",
        stops: [
          { name: "Sasthamkotta Lake", lat: 9.04, lng: 76.63 },
          { name: "Jatayu Earth's Center", lat: 8.869, lng: 76.867 },
        ],
      },
      {
        title: "The long boat to Alappuzha",
        morning: "Board the tourist boat from Kollam to Alappuzha, usually leaving around 10:30 am.",
        afternoon: "About 8 hrs through Ashtamudi, Kayamkulam lake and village canals, with a stop near Amritapuri.",
        evening: "Arrive in Alappuzha around dusk.",
        stay: "Alappuzha",
        tip: "Confirm timings with DTPC Kollam a day ahead. Carry water, sunscreen and a hat; the deck gets hot.",
        stops: [
          { name: "Kollam Boat Jetty", lat: 8.887, lng: 76.593 },
          { name: "Amritapuri", lat: 9.094, lng: 76.49 },
        ],
      },
      {
        title: "Alappuzha and depart",
        morning: "Alappuzha beach and the town canals.",
        afternoon: "Train from Alappuzha or drive about 2 hrs to Kochi airport.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Alappuzha Beach", lat: 9.493, lng: 76.317 }],
      },
    ],
  },
  {
    slug: "sundarbans",
    featured: true,
    name: "Sundarbans",
    state: "West Bengal",
    tagline: "Tiger country by boat",
    summary: "The world's largest mangrove forest, explored by boat through creeks shared with tigers and crocodiles.",
    tourType: "wildlife",
    lat: 22.125,
    lng: 88.82,
    bestTime: {
      months: "Nov – Feb",
      note: "Cool, dry and calm water. Summer is very humid, and the monsoon brings storms and rough rivers.",
    },
    bestMonths: [11, 12, 1, 2],
    howToReach:
      "Fly or take a train to Kolkata. Drive about 3 hrs to Godkhali jetty, then boat to Gosaba or Pakhiralaya. Most visitors go on a boat package from Kolkata.",
    budgetPerDay: { budget: "₹2,500–4,000", mid: "₹5,000–8,000", premium: "₹12,000+" },
    facts: [
      { label: "Landscape", value: "Mangrove delta" },
      { label: "Access", value: "Boat only" },
      { label: "Best time", value: "Nov–Feb" },
      { label: "Famous for", value: "Bengal tiger" },
    ],
    experiences: [
      { name: "Creek safari by boat", duration: "Full day", icon: "boat" },
      { name: "Watchtower wildlife", duration: "1 hr each", icon: "binoculars" },
      { name: "Village evening", duration: "2 hrs", icon: "music" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Kolkata to the delta",
        morning: "Leave Kolkata by 7 am and drive about 3 hrs to Godkhali jetty.",
        afternoon: "Boat past Gosaba to Pakhiralaya; lunch on board.",
        evening: "Village walk and a folk performance about Bonbibi, the forest goddess.",
        stay: "Lodge at Pakhiralaya",
        tip: "Forest permits come from the West Bengal forest department. Most operators arrange them; carry your ID.",
        stops: [
          { name: "Godkhali jetty", lat: 22.17, lng: 88.77 },
          { name: "Gosaba", lat: 22.165, lng: 88.807 },
          { name: "Pakhiralaya", lat: 22.125, lng: 88.818 },
        ],
      },
      {
        title: "Sajnekhali and Sudhanyakhali",
        morning: "Sajnekhali watchtower, interpretation centre and the mangrove nursery.",
        afternoon: "Cruise the creeks to Sudhanyakhali watchtower, one of the better spots for tiger and deer.",
        evening: "Back before dark; boats cannot stay in the forest at night.",
        stay: "Lodge at Pakhiralaya",
        tip: "Tiger sightings are rare. Look for crocodiles, monitor lizards, spotted deer and kingfishers instead.",
        stops: [
          { name: "Sajnekhali", lat: 22.123, lng: 88.828 },
          { name: "Sudhanyakhali", lat: 22.115, lng: 88.88 },
        ],
      },
      {
        title: "Dobanki and Netidhopani",
        morning: "Long boat day. Dobanki canopy walk, a caged walkway above the mangroves.",
        afternoon: "Netidhopani, with the ruins of an old temple deep in the forest.",
        evening: "Return to the lodge.",
        stay: "Lodge at Pakhiralaya",
        tip: "These spots need extra permits and a forest guide. Ask your operator to arrange them in advance.",
        stops: [
          { name: "Dobanki", lat: 22.05, lng: 88.92 },
          { name: "Netidhopani", lat: 21.95, lng: 88.93 },
        ],
      },
      {
        title: "Village life",
        morning: "Walk the embankments of Bali or Gosaba island.",
        afternoon: "Meet honey collectors and fishing families; see how people live with tidal water.",
        evening: "Sunset from the boat deck.",
        stay: "Lodge at Pakhiralaya",
        stops: [{ name: "Gosaba", lat: 22.165, lng: 88.807 }],
      },
      {
        title: "Back to Kolkata",
        morning: "Last short creek cruise at dawn.",
        afternoon: "Boat to Godkhali and drive back to Kolkata.",
        evening: "Rest in Kolkata.",
        stay: "Kolkata",
        stops: [{ name: "Godkhali jetty", lat: 22.17, lng: 88.77 }],
      },
      {
        title: "Kolkata and depart",
        morning: "Victoria Memorial and the Maidan.",
        afternoon: "Head to the airport or Howrah station.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Victoria Memorial", lat: 22.5448, lng: 88.3426 }],
      },
    ],
  },
  {
    slug: "bandhavgarh",
    name: "Bandhavgarh",
    state: "Madhya Pradesh",
    tagline: "Tigers in sal forest",
    summary: "Sal forest, meadows and an old hill fort, with some of the best tiger sighting odds in India.",
    tourType: "wildlife",
    lat: 23.719,
    lng: 81.024,
    bestTime: {
      months: "Oct – Jun",
      note: "Core zones close Jul–Sep. Winter mornings are near freezing; Apr–Jun is hot but tigers stay near waterholes.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3, 4, 5, 6],
    howToReach:
      "Umaria station is about 35 km from Tala; Katni is about 100 km. The nearest airport is Jabalpur (JLR), around 4–5 hrs by road.",
    budgetPerDay: { budget: "₹2,500–4,000", mid: "₹6,000–10,000", premium: "₹20,000+" },
    facts: [
      { label: "Landscape", value: "Sal forest" },
      { label: "Core zones", value: "Tala, Magadhi, Khitauli" },
      { label: "Closed", value: "Jul–Sep" },
      { label: "Famous for", value: "Tigers" },
    ],
    experiences: [
      { name: "Jeep safari", duration: "4–5 hrs", icon: "binoculars" },
      { name: "Birding in the buffer", duration: "3 hrs", icon: "leaf" },
      { name: "Tala village walk", duration: "1–2 hrs", icon: "hike" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive in Tala",
        morning: "Reach Umaria or Katni and drive to Tala village, the main base by the park.",
        afternoon: "Check in and rest.",
        evening: "Walk around Tala village and turn in early.",
        stay: "Tala",
        tip: "Book safaris on the official MP Forest online portal as soon as dates open. Popular zones sell out months ahead.",
        stops: [{ name: "Tala", lat: 23.719, lng: 81.024 }],
      },
      {
        title: "Tala zone",
        morning: "Morning safari in Tala, the most popular zone, with meadows and views of Bandhavgarh hill.",
        afternoon: "Rest at the lodge through the heat.",
        evening: "Afternoon safari in Magadhi zone.",
        stay: "Tala",
        tip: "Carry your original ID used for booking. Winter mornings in an open jeep are very cold; bring a warm jacket and gloves.",
        stops: [
          { name: "Tala gate", lat: 23.72, lng: 81.02 },
          { name: "Magadhi gate", lat: 23.725, lng: 81.012 },
        ],
      },
      {
        title: "Khitauli zone",
        morning: "Morning safari in Khitauli, usually less crowded than Tala.",
        afternoon: "Rest, or visit the small Baghel Museum in Tala.",
        evening: "Quiet evening at the lodge.",
        stay: "Tala",
        stops: [{ name: "Khitauli gate", lat: 23.78, lng: 80.96 }],
      },
      {
        title: "Buffer zone",
        morning: "Safari in a buffer zone such as Panpatha or Johila; good for birds and often for tigers too.",
        afternoon: "Rest.",
        evening: "Village walk with a local guide.",
        stay: "Tala",
        tip: "Buffer zone permits are cheaper and easier to get at short notice.",
        stops: [{ name: "Tala", lat: 23.719, lng: 81.024 }],
      },
      {
        title: "One more core safari",
        morning: "A second Tala or Magadhi safari; each drive takes a different route.",
        afternoon: "Rest and sort photos.",
        evening: "Last evening in Tala.",
        stay: "Tala",
        stops: [{ name: "Tala gate", lat: 23.72, lng: 81.02 }],
      },
      {
        title: "Depart",
        morning: "Early birding walk around Tala.",
        afternoon: "Drive to Umaria, Katni or Jabalpur for your onward journey.",
        evening: "Departure.",
        stay: "—",
        stops: [
          { name: "Umaria station", lat: 23.525, lng: 80.837 },
          { name: "Katni Junction", lat: 23.834, lng: 80.394 },
        ],
      },
    ],
  },
];
