import type { Destination } from "../types";

// Seed content. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const extraHills: Destination[] = [
  {
    slug: "coorg",
    name: "Coorg",
    state: "Karnataka",
    tagline: "Coffee country of the south",
    summary:
      "Misty coffee estates, waterfalls, a Tibetan settlement and the source of the Kaveri in the Western Ghats.",
    tourType: "hills",
    lat: 12.4244,
    lng: 75.7382,
    bestTime: {
      months: "Oct – Mar",
      note: "Cool, dry days and estates in bloom by Feb–Mar. Monsoon (Jun–Sep) is very wet with leeches on trails.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "No airport or railway in Coorg. Fly to Mangaluru, Kannur or Bengaluru, or take a train to Mysuru, then 3–6 hrs by road to Madikeri.",
    budgetPerDay: { budget: "₹2,000–3,000", mid: "₹5,000–8,000", premium: "₹15,000+" },
    facts: [
      { label: "Altitude", value: "1,150 m" },
      { label: "Landscape", value: "Coffee estates" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Coffee" },
    ],
    experiences: [
      { name: "Coffee plantation walk", duration: "2 hrs", icon: "leaf" },
      { name: "Dubare elephant camp", duration: "2–3 hrs", icon: "binoculars" },
      { name: "Namdroling Golden Temple", duration: "1–2 hrs", icon: "temple" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive in Madikeri",
        morning: "Drive in from Mysuru, Mangaluru or Bengaluru through the ghats.",
        afternoon: "Check in at an estate homestay. Walk up to Madikeri Fort and the Omkareshwara Temple.",
        evening: "Sunset over the valleys from Raja's Seat garden.",
        stay: "Madikeri or a nearby estate homestay",
        tip: "Homestays inside plantations are the best way to stay here. Book ahead for long weekends.",
        stops: [
          { name: "Madikeri Fort", lat: 12.4215, lng: 75.7393 },
          { name: "Raja's Seat", lat: 12.4198, lng: 75.7381 },
        ],
      },
      {
        title: "Falls and a coffee estate",
        morning: "Abbey Falls, a short walk down through coffee and pepper vines.",
        afternoon: "Guided plantation walk: coffee picking (Dec–Feb), pepper, cardamom and how beans are processed.",
        evening: "Coorgi dinner at your homestay: pandi curry and kadambuttu.",
        stay: "Madikeri or a nearby estate homestay",
        tip: "Abbey Falls is on private estate land; go early to avoid the crowds.",
        stops: [{ name: "Abbey Falls", lat: 12.4547, lng: 75.7155 }],
      },
      {
        title: "Elephants and the Golden Temple",
        morning: "Drive 40 km to Dubare elephant camp on the Kaveri. Elephant bathing happens early, so arrive by 8:30.",
        afternoon: "Kaveri Nisargadhama bamboo island, then Namdroling Monastery at Bylakuppe.",
        evening: "Tibetan momos and thukpa in the Bylakuppe settlement before heading back.",
        stay: "Madikeri or Kushalnagar",
        tip: "Dubare has seasonal closures and changing activity timings. Check before you go.",
        stops: [
          { name: "Dubare Elephant Camp", lat: 12.369, lng: 75.906 },
          { name: "Kaveri Nisargadhama", lat: 12.4975, lng: 75.968 },
          { name: "Namdroling Monastery", lat: 12.4316, lng: 75.9677 },
        ],
      },
      {
        title: "Source of the Kaveri",
        morning: "Drive 45 km to Bhagamandala, where three rivers meet, and its Kerala-style temple.",
        afternoon: "Climb on to Talakaveri, the source of the Kaveri, with wide views over the Brahmagiri hills.",
        evening: "Back to Madikeri for an easy evening.",
        stay: "Madikeri or a nearby estate homestay",
        tip: "Dress modestly for both temples. Talakaveri is often in cloud after noon.",
        stops: [
          { name: "Bhagamandala", lat: 12.386, lng: 75.53 },
          { name: "Talakaveri", lat: 12.385, lng: 75.494 },
        ],
      },
      {
        title: "South Coorg and Iruppu Falls",
        morning: "Drive south through Virajpet and Gonikoppal estate country.",
        afternoon: "Iruppu Falls in the Brahmagiri forest, a short forest walk from the road.",
        evening: "Stay at a south Coorg estate for a quiet night.",
        stay: "South Coorg estate homestay",
        stops: [{ name: "Iruppu Falls", lat: 11.968, lng: 75.987 }],
      },
      {
        title: "Coffee shopping and depart",
        morning: "Buy fresh coffee, pepper, honey and homemade wine from estate shops.",
        afternoon: "Drive out. If leaving via Mysuru, stop at Mysuru Palace on the way.",
        evening: "Departure.",
        stay: "—",
        tip: "Coorg to Bengaluru takes 5–6 hrs; leave by noon for an evening flight.",
        stops: [{ name: "Mysuru Palace", lat: 12.3052, lng: 76.6552 }],
      },
    ],
  },
  {
    slug: "meghalaya",
    name: "Shillong & Cherrapunji",
    state: "Meghalaya",
    tagline: "Abode of the clouds",
    summary:
      "Living root bridges, deep green gorges, the clear Umngot river at Dawki and Asia's cleanest village.",
    tourType: "hills",
    lat: 25.5788,
    lng: 91.8933,
    bestTime: {
      months: "Oct – May",
      note: "Dry, clear days and a glassy Umngot river (Nov–Apr). Jun–Sep brings some of the heaviest rain on earth.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3, 4, 5],
    howToReach:
      "Fly or take a train to Guwahati, then 3 hrs by road (100 km) to Shillong. Shared Sumos and private taxis run all day.",
    budgetPerDay: { budget: "₹1,800–3,000", mid: "₹4,000–7,000", premium: "₹10,000+" },
    facts: [
      { label: "Altitude", value: "1,525 m" },
      { label: "Landscape", value: "Gorges, falls" },
      { label: "Best time", value: "Oct–May" },
      { label: "Famous for", value: "Root bridges" },
    ],
    experiences: [
      { name: "Double-decker root bridge trek", duration: "5–6 hrs", icon: "hike" },
      { name: "Boat ride on the Umngot", duration: "1 hr", icon: "boat" },
      { name: "Nohkalikai Falls viewpoint", duration: "1 hr", icon: "camera" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Guwahati to Shillong",
        morning: "Land in Guwahati and drive up to Shillong (about 3 hrs).",
        afternoon: "Stop at Umiam Lake on the way for the view over the reservoir.",
        evening: "Walk Police Bazaar and try jadoh and local tea.",
        stay: "Shillong",
        tip: "Hire a taxi from Guwahati for the whole trip; public transport to the villages is limited.",
        stops: [
          { name: "Umiam Lake", lat: 25.655, lng: 91.887 },
          { name: "Police Bazaar", lat: 25.5765, lng: 91.8826 },
        ],
      },
      {
        title: "Shillong sights",
        morning: "Elephant Falls, three tiers of water just outside town.",
        afternoon: "Don Bosco Museum, seven floors on the cultures of the Northeast.",
        evening: "Ward's Lake, then live music at one of Shillong's cafés.",
        stay: "Shillong",
        tip: "Many shops and some sights in Shillong close on Sundays.",
        stops: [
          { name: "Elephant Falls", lat: 25.5375, lng: 91.8267 },
          { name: "Don Bosco Museum", lat: 25.5683, lng: 91.8996 },
          { name: "Ward's Lake", lat: 25.5763, lng: 91.8875 },
        ],
      },
      {
        title: "Cherrapunji falls and caves",
        morning: "Drive 55 km to Sohra (Cherrapunji), stopping at the Mawkdok Dympep valley viewpoint.",
        afternoon: "Nohkalikai Falls, India's tallest plunge waterfall, then Mawsmai Cave.",
        evening: "Seven Sisters Falls at sunset if the sky is clear.",
        stay: "Sohra",
        tip: "Falls are fullest Jun–Oct but often hidden in cloud. Mornings are clearer.",
        stops: [
          { name: "Nohkalikai Falls", lat: 25.274, lng: 91.687 },
          { name: "Mawsmai Cave", lat: 25.247, lng: 91.731 },
        ],
      },
      {
        title: "Double-decker root bridge",
        morning: "Start early from Tyrna and walk down about 3,500 steps to Nongriat.",
        afternoon: "The double-decker root bridge and the blue pools nearby, then the climb back up.",
        evening: "Rest in Sohra. Your legs will feel it.",
        stay: "Sohra",
        tip: "Allow 5–6 hrs round trip. Wear shoes with grip; the steps are wet most of the year.",
        stops: [{ name: "Nongriat root bridge", lat: 25.245, lng: 91.678 }],
      },
      {
        title: "Mawlynnong and Dawki",
        morning: "Drive to Mawlynnong, the village known for being the cleanest in Asia, and the Riwai root bridge.",
        afternoon: "Boat ride on the Umngot at Dawki, where the water is clear enough to see the riverbed.",
        evening: "Drive back to Shillong (about 3 hrs).",
        stay: "Shillong",
        tip: "Boating is often stopped in peak monsoon. The water is clearest Nov–Apr.",
        stops: [
          { name: "Mawlynnong", lat: 25.2017, lng: 91.9167 },
          { name: "Dawki", lat: 25.1832, lng: 92.0181 },
        ],
      },
      {
        title: "Sacred forest and depart",
        morning: "Mawphlang Sacred Forest with a local guide.",
        afternoon: "Drive to Guwahati for your onward flight or train.",
        evening: "Departure.",
        stay: "—",
        tip: "Keep 4 hrs from Shillong to Guwahati airport; traffic at Jorabat can be slow.",
        stops: [{ name: "Mawphlang Sacred Forest", lat: 25.448, lng: 91.758 }],
      },
    ],
  },
  {
    slug: "nainital",
    name: "Nainital",
    state: "Uttarakhand",
    tagline: "Lake town of Kumaon",
    summary: "A hill town wrapped around Naini Lake, with nearby lakes, orchards and Himalayan views from Mukteshwar.",
    tourType: "hills",
    lat: 29.3803,
    lng: 79.4636,
    bestTime: {
      months: "Mar – Jun, Sep – Nov",
      note: "Pleasant days and clear autumn views. Winters are cold with occasional snow; monsoon brings landslides.",
    },
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    howToReach:
      "Train to Kathgodam, then 1.5 hrs (35 km) by road. Pantnagar is the nearest airport, about 2 hrs away. Overnight buses run from Delhi.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "2,084 m" },
      { label: "Landscape", value: "Lakes, oak forest" },
      { label: "Best time", value: "Mar–Jun" },
      { label: "Famous for", value: "Naini Lake" },
    ],
    experiences: [
      { name: "Boating on Naini Lake", duration: "1 hr", icon: "boat" },
      { name: "Ropeway to Snow View", duration: "2 hrs", icon: "mountain" },
      { name: "Naina Peak hike", duration: "3–4 hrs", icon: "hike" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive at the lake",
        morning: "Reach Kathgodam and drive up to Nainital.",
        afternoon: "Check in and take a rowing boat or yacht out on Naini Lake.",
        evening: "Walk Mall Road from Tallital to Mallital.",
        stay: "Near Mall Road",
        tip: "On summer weekends traffic and parking are very tight. Arrive early or leave the car at your hotel.",
        stops: [{ name: "Naini Lake", lat: 29.3919, lng: 79.4542 }],
      },
      {
        title: "Temple and Snow View",
        morning: "Naina Devi Temple at the north end of the lake.",
        afternoon: "Ropeway from Mallital to Snow View Point for Himalayan views on a clear day.",
        evening: "Tibetan market and the flats by the lake.",
        stay: "Near Mall Road",
        tip: "Ropeway queues are long in May–June. Go at opening time.",
        stops: [
          { name: "Naina Devi Temple", lat: 29.3946, lng: 79.4562 },
          { name: "Snow View Point", lat: 29.396, lng: 79.46 },
        ],
      },
      {
        title: "The lake circuit",
        morning: "Drive to Bhimtal, the largest lake in the area, and boat to its island.",
        afternoon: "Naukuchiatal, then the quiet forest lakes of Sattal.",
        evening: "Back to Nainital.",
        stay: "Near Mall Road",
        stops: [
          { name: "Bhimtal", lat: 29.3463, lng: 79.5622 },
          { name: "Naukuchiatal", lat: 29.3233, lng: 79.5878 },
          { name: "Sattal", lat: 29.355, lng: 79.535 },
        ],
      },
      {
        title: "Mukteshwar day trip",
        morning: "Drive 50 km to Mukteshwar through orchards.",
        afternoon: "Mukteshwar Dham temple and the cliffs at Chauli ki Jali, with wide snow-peak views.",
        evening: "Return to Nainital.",
        stay: "Near Mall Road",
        tip: "Oct–Nov gives the clearest views of the Nanda Devi range.",
        stops: [{ name: "Mukteshwar", lat: 29.4722, lng: 79.6479 }],
      },
      {
        title: "Naina Peak and Tiffin Top",
        morning: "Hike to Naina Peak, the highest point around town, for views over the lake and the Himalaya.",
        afternoon: "Walk or ride a pony to Tiffin Top (Dorothy's Seat).",
        evening: "Early dinner and a slow walk by the lake.",
        stay: "Near Mall Road",
        stops: [
          { name: "Naina Peak", lat: 29.4012, lng: 79.4392 },
          { name: "Tiffin Top", lat: 29.3713, lng: 79.4389 },
        ],
      },
      {
        title: "Kainchi Dham and depart",
        morning: "Visit Kainchi Dham ashram, 17 km away on the Almora road.",
        afternoon: "Drive down to Kathgodam via Bhowali for your train or onward bus.",
        evening: "Departure.",
        stay: "—",
        tip: "Kainchi Dham is very crowded on weekends and around 15 June. Go on a weekday morning.",
        stops: [
          { name: "Kainchi Dham", lat: 29.424, lng: 79.517 },
          { name: "Kathgodam station", lat: 29.2695, lng: 79.5435 },
        ],
      },
    ],
  },
  {
    slug: "mussoorie",
    name: "Mussoorie",
    state: "Uttarakhand",
    tagline: "Ridge town above Doon",
    summary: "A ridge-top town above Dehradun with colonial Landour, Doon Valley views and easy day trips to Dhanaulti.",
    tourType: "hills",
    lat: 30.4598,
    lng: 78.0644,
    bestTime: {
      months: "Mar – Jun, Sep – Nov",
      note: "Mild days and clear views in autumn. Snow is possible Dec–Jan; monsoon brings fog and landslides.",
    },
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    howToReach:
      "Train or fly to Dehradun (Jolly Grant airport), then 1–1.5 hrs (35 km) uphill by taxi or bus.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "2,005 m" },
      { label: "Landscape", value: "Ridges, deodar" },
      { label: "Best time", value: "Mar–Jun" },
      { label: "Famous for", value: "Landour" },
    ],
    experiences: [
      { name: "Landour heritage walk", duration: "3 hrs", icon: "hike" },
      { name: "Gun Hill ropeway", duration: "1 hr", icon: "mountain" },
      { name: "Char Dukan snacks", duration: "1 hr", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and walk the Mall",
        morning: "Reach Dehradun and drive up to Mussoorie.",
        afternoon: "Check in and take the ropeway up to Gun Hill for views over the Doon Valley.",
        evening: "Walk Mall Road from Library Chowk to Kulri Bazaar.",
        stay: "Near Mall Road",
        tip: "Weekend traffic from Dehradun can add 2 hrs. Arrive on a weekday if you can.",
        stops: [
          { name: "Gun Hill", lat: 30.4594, lng: 78.0756 },
          { name: "Mall Road", lat: 30.4583, lng: 78.0703 },
        ],
      },
      {
        title: "Landour",
        morning: "Walk up to Landour through Sister's Bazaar and the old cantonment lanes.",
        afternoon: "Char Dukan for pancakes and Maggi, then Lal Tibba viewpoint for the snow peaks.",
        evening: "St Paul's Church and a quiet walk back down.",
        stay: "Near Mall Road or Landour",
        tip: "Landour roads are narrow and steep. Walk rather than drive.",
        stops: [
          { name: "Char Dukan", lat: 30.456, lng: 78.094 },
          { name: "Lal Tibba", lat: 30.4567, lng: 78.0947 },
        ],
      },
      {
        title: "Kempty Falls and Company Garden",
        morning: "Kempty Falls, 15 km out on the Yamunotri road.",
        afternoon: "Company Garden for a slow afternoon among flower beds.",
        evening: "Sunset walk on Camel's Back Road.",
        stay: "Near Mall Road",
        tip: "Kempty is packed by 11 am in summer. Go at 8 am.",
        stops: [
          { name: "Kempty Falls", lat: 30.4875, lng: 78.0215 },
          { name: "Company Garden", lat: 30.4705, lng: 78.0527 },
        ],
      },
      {
        title: "Dhanaulti and Surkanda Devi",
        morning: "Drive 25 km to Dhanaulti through deodar forest and walk the eco parks.",
        afternoon: "Climb to Surkanda Devi temple (by foot or ropeway) for wide Himalayan views.",
        evening: "Return to Mussoorie.",
        stay: "Near Mall Road",
        stops: [
          { name: "Dhanaulti", lat: 30.4277, lng: 78.2425 },
          { name: "Surkanda Devi", lat: 30.4106, lng: 78.2888 },
        ],
      },
      {
        title: "George Everest's House",
        morning: "Drive to Park Estate and the restored house of Sir George Everest.",
        afternoon: "Walk the open ridge around it for views of the Aglar valley and the snow peaks.",
        evening: "Café dinner in Kulri.",
        stay: "Near Mall Road",
        stops: [{ name: "George Everest's House", lat: 30.444, lng: 78.023 }],
      },
      {
        title: "Robber's Cave and depart",
        morning: "Drive down to Dehradun.",
        afternoon: "Robber's Cave (Guchhupani), a short walk through a stream inside a narrow gorge.",
        evening: "Departure from Dehradun.",
        stay: "—",
        tip: "Wear sandals at Robber's Cave; you will walk through ankle-deep water.",
        stops: [{ name: "Robber's Cave", lat: 30.3768, lng: 78.0603 }],
      },
    ],
  },
  {
    slug: "kodaikanal",
    name: "Kodaikanal",
    state: "Tamil Nadu",
    tagline: "Princess of hill stations",
    summary: "A star-shaped lake, pine forests and cliff-edge views in the Palani hills of Tamil Nadu.",
    tourType: "hills",
    lat: 10.2381,
    lng: 77.4892,
    bestTime: {
      months: "Mar – Jun, Sep – Oct",
      note: "Cool, mostly clear days. Oct–Dec brings the northeast monsoon; winter nights drop close to freezing.",
    },
    bestMonths: [3, 4, 5, 6, 9, 10],
    howToReach:
      "Fly to Madurai (120 km) or take a train to Kodai Road (80 km), then 3–4 hrs up the ghat road.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–6,500", premium: "₹10,000+" },
    facts: [
      { label: "Altitude", value: "2,133 m" },
      { label: "Landscape", value: "Pine, cliffs" },
      { label: "Best time", value: "Mar–Jun" },
      { label: "Famous for", value: "Kodai Lake" },
    ],
    experiences: [
      { name: "Cycle around Kodai Lake", duration: "1 hr", icon: "bike" },
      { name: "Dolphin's Nose walk", duration: "3 hrs", icon: "hike" },
      { name: "Homemade chocolate shopping", duration: "1 hr", icon: "shopping" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Up the ghat road",
        morning: "Drive up from Madurai or Kodai Road.",
        afternoon: "Stop at Silver Cascade falls on the ghat road, then check in.",
        evening: "Walk the town market and pick up homemade chocolates.",
        stay: "Near Kodai Lake",
        tip: "Tamil Nadu has required an e-pass for vehicles entering Kodaikanal in recent seasons. Check before you travel.",
        stops: [
          { name: "Silver Cascade", lat: 10.2489, lng: 77.5156 },
          { name: "Kodai Lake", lat: 10.234, lng: 77.488 },
        ],
      },
      {
        title: "Coaker's Walk and the lake",
        morning: "Coaker's Walk early, before cloud fills the valley below.",
        afternoon: "Bryant Park, then hire a cycle for the 5 km loop around the lake or take a boat.",
        evening: "Hot snacks by the lake boat club.",
        stay: "Near Kodai Lake",
        stops: [
          { name: "Coaker's Walk", lat: 10.2319, lng: 77.495 },
          { name: "Bryant Park", lat: 10.2318, lng: 77.4925 },
        ],
      },
      {
        title: "Pine forest and Pillar Rocks",
        morning: "Pine Forest and Guna Caves (viewed from the fenced path).",
        afternoon: "Pillar Rocks, three granite columns rising from the valley, and Moir Point.",
        evening: "Back in town for dinner.",
        stay: "Near Kodai Lake",
        tip: "These spots sit on one road; a taxi does the full loop in about 4 hrs.",
        stops: [
          { name: "Pine Forest", lat: 10.2228, lng: 77.4767 },
          { name: "Guna Caves", lat: 10.2133, lng: 77.4675 },
          { name: "Pillar Rocks", lat: 10.217, lng: 77.473 },
        ],
      },
      {
        title: "Dolphin's Nose",
        morning: "Drive to Vattakanal and walk down to Dolphin's Nose, a rock ledge over a sheer drop.",
        afternoon: "Lunch in Vattakanal, then Kurinji Andavar Temple on the other side of town.",
        evening: "Quiet evening near the lake.",
        stay: "Near Kodai Lake",
        tip: "The path is rocky and slippery after rain. Keep away from the unfenced edge.",
        stops: [
          { name: "Dolphin's Nose", lat: 10.2072, lng: 77.4914 },
          { name: "Kurinji Andavar Temple", lat: 10.2475, lng: 77.5108 },
        ],
      },
      {
        title: "Poombarai village",
        morning: "Drive 18 km to Poombarai, a village of terraced garlic and vegetable fields.",
        afternoon: "Kuzhanthai Velappar Temple and a walk through the terraces.",
        evening: "Return to Kodaikanal.",
        stay: "Near Kodai Lake",
        stops: [{ name: "Poombarai", lat: 10.2333, lng: 77.3889 }],
      },
      {
        title: "Palani and depart",
        morning: "Drive down the Palani ghat road.",
        afternoon: "Palani hill temple by winch or rope car, then on to Madurai or Coimbatore.",
        evening: "Departure.",
        stay: "—",
        tip: "Palani is very busy on festival days; allow extra time for the queues.",
        stops: [{ name: "Palani hill temple", lat: 10.4393, lng: 77.5205 }],
      },
    ],
  },
  {
    slug: "tawang",
    name: "Tawang",
    state: "Arunachal Pradesh",
    tagline: "Monastery above the clouds",
    summary: "India's largest monastery, the high Sela Pass and frozen lakes near the Tibet border.",
    tourType: "mountain",
    lat: 27.586,
    lng: 91.8594,
    bestTime: {
      months: "Mar – May, Sep – Nov",
      note: "Clear skies and open roads. Jun–Aug brings landslides; Dec–Feb is snowy and some high areas close.",
    },
    bestMonths: [3, 4, 5, 9, 10, 11],
    howToReach:
      "Fly or take a train to Guwahati or Tezpur, then two days by road via Bhalukpong and Dirang. Indians need an Inner Line Permit (ILP).",
    budgetPerDay: { budget: "₹2,500–4,000", mid: "₹5,000–8,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "3,050 m" },
      { label: "Permit", value: "ILP required" },
      { label: "Best time", value: "Mar–May" },
      { label: "Famous for", value: "Tawang Monastery" },
    ],
    experiences: [
      { name: "Tawang Monastery prayers", duration: "2 hrs", icon: "temple" },
      { name: "Crossing Sela Pass", duration: "3 hrs", icon: "mountain" },
      { name: "Madhuri Lake drive", duration: "Full day", icon: "camera" },
    ],
    minDays: 4,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Into Arunachal to Dirang",
        morning: "Leave Tezpur or Guwahati early and cross into Arunachal at Bhalukpong, where permits are checked.",
        afternoon: "Climb through Bomdila to the Dirang valley.",
        evening: "Rest in Dirang after a long drive.",
        stay: "Dirang",
        tip: "Apply for the e-ILP online before the trip and carry printed copies. Foreign nationals need a Protected Area Permit.",
        stops: [
          { name: "Bhalukpong", lat: 27.01, lng: 92.65 },
          { name: "Dirang", lat: 27.3584, lng: 92.2409 },
        ],
      },
      {
        title: "Over Sela Pass to Tawang",
        morning: "Cross Sela Pass (4,170 m) and its lake. Stop briefly; the air is thin.",
        afternoon: "Jaswant Garh war memorial and Nuranang Falls near Jang.",
        evening: "Reach Tawang and rest.",
        stay: "Tawang",
        tip: "The Sela Tunnel keeps the road open in winter. Take the old pass road for the views when it is clear.",
        stops: [
          { name: "Sela Pass", lat: 27.505, lng: 92.106 },
          { name: "Jaswant Garh", lat: 27.535, lng: 92.16 },
          { name: "Nuranang Falls", lat: 27.5383, lng: 92.035 },
        ],
      },
      {
        title: "Tawang Monastery",
        morning: "Tawang Monastery, India's largest, during morning prayers. See the museum and library.",
        afternoon: "Tawang War Memorial for the 1962 war.",
        evening: "Light and sound show at the war memorial, then the old market.",
        stay: "Tawang",
        tip: "Take it easy on the first full day at this altitude and drink plenty of water.",
        stops: [
          { name: "Tawang Monastery", lat: 27.5883, lng: 91.8571 },
          { name: "Tawang War Memorial", lat: 27.5845, lng: 91.8695 },
        ],
      },
      {
        title: "Bum La and Madhuri Lake",
        morning: "Drive north past high lakes to Bum La on the India–China border.",
        afternoon: "Madhuri (Sangetsar) Lake, with dead trees standing in still water.",
        evening: "Back to Tawang.",
        stay: "Tawang",
        tip: "Bum La needs a separate permit from the DC office in Tawang and is open to Indian citizens only. It closes after heavy snow.",
        stops: [{ name: "Madhuri Lake", lat: 27.73, lng: 91.84 }],
      },
      {
        title: "Back to Dirang",
        morning: "Leave Tawang and cross back over Sela.",
        afternoon: "Dirang Dzong, the old stone village, and the hot water springs.",
        evening: "Rest in Dirang.",
        stay: "Dirang",
        stops: [{ name: "Dirang", lat: 27.3584, lng: 92.2409 }],
      },
      {
        title: "Bomdila and depart",
        morning: "Bomdila Monastery on the way down.",
        afternoon: "Drive on to Tezpur or Guwahati.",
        evening: "Departure, or a night in Tezpur if your flight is next day.",
        stay: "—",
        tip: "Dirang to Guwahati takes 9–10 hrs. Book onward travel for the next morning to be safe.",
        stops: [{ name: "Bomdila", lat: 27.2645, lng: 92.4159 }],
      },
    ],
  },
  {
    slug: "kasol",
    name: "Kasol & Parvati Valley",
    state: "Himachal Pradesh",
    tagline: "Riverside trails and cafés",
    summary: "Pine-lined riverside villages, the hot springs of Manikaran and the trek to Kheerganga.",
    tourType: "mountain",
    lat: 32.01,
    lng: 77.315,
    bestTime: {
      months: "Mar – Jun, Sep – Nov",
      note: "Good trekking weather. Monsoon (Jul–Aug) brings landslides; winter is cold and Kheerganga is snowed in.",
    },
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    howToReach:
      "Overnight bus from Delhi to Bhuntar, then 1 hr (31 km) by taxi or local bus. Kullu–Manali airport at Bhuntar has limited flights.",
    budgetPerDay: { budget: "₹1,200–2,000", mid: "₹3,000–5,000", premium: "₹8,000+" },
    facts: [
      { label: "Altitude", value: "1,580 m" },
      { label: "Kheerganga", value: "2,950 m" },
      { label: "Best time", value: "Mar–Jun" },
      { label: "Famous for", value: "Treks, cafés" },
    ],
    experiences: [
      { name: "Kheerganga trek", duration: "2 days", icon: "hike" },
      { name: "Manikaran langar", duration: "1–2 hrs", icon: "temple" },
      { name: "Israeli café food", duration: "1 hr", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive in Kasol",
        morning: "Reach Bhuntar on the overnight bus and drive up the Parvati valley.",
        afternoon: "Cross the bridge to Chalal and walk the trail along the river.",
        evening: "Café dinner in Kasol market: shakshuka, falafel or trout.",
        stay: "Kasol",
        tip: "Book a riverside guest house; it is quieter than the main road.",
        stops: [
          { name: "Kasol", lat: 32.01, lng: 77.315 },
          { name: "Chalal", lat: 32.0063, lng: 77.3109 },
        ],
      },
      {
        title: "Manikaran",
        morning: "Drive or walk 4 km to Manikaran.",
        afternoon: "Manikaran Sahib gurudwara with its hot springs and free langar, and the Ram temple.",
        evening: "Back to Kasol.",
        stay: "Kasol",
        tip: "Cover your head at the gurudwara. The spring water is scalding; only use the bathing pools.",
        stops: [{ name: "Manikaran Sahib", lat: 32.027, lng: 77.3487 }],
      },
      {
        title: "Trek to Kheerganga",
        morning: "Drive to Barshaini (1 hr) and start the 12 km trek via Nakthan.",
        afternoon: "Climb through forest and past waterfalls to the Kheerganga meadow (5–6 hrs total).",
        evening: "Soak in the hot spring pool at the top.",
        stay: "Kheerganga",
        tip: "Camping rules at Kheerganga change often. Confirm with your guest house and carry warm layers.",
        stops: [
          { name: "Barshaini", lat: 32.017, lng: 77.42 },
          { name: "Kheerganga", lat: 31.995, lng: 77.51 },
        ],
      },
      {
        title: "Down from Kheerganga",
        morning: "Sunrise over the peaks and a morning dip in the hot pool.",
        afternoon: "Walk down to Barshaini and drive back.",
        evening: "Rest in Kasol.",
        stay: "Kasol",
        stops: [{ name: "Kheerganga", lat: 31.995, lng: 77.51 }],
      },
      {
        title: "Kalga and Pulga",
        morning: "Drive to Barshaini and walk up to Kalga, a village of apple orchards.",
        afternoon: "Walk on to Pulga and its old deodar forest.",
        evening: "Night in a village guest house.",
        stay: "Kalga or Pulga",
        stops: [
          { name: "Kalga", lat: 32.023, lng: 77.425 },
          { name: "Pulga", lat: 32.0198, lng: 77.4302 },
        ],
      },
      {
        title: "Tosh and depart",
        morning: "Walk or drive up to Tosh for views of the snow peaks at the head of the valley.",
        afternoon: "Drive down to Bhuntar (about 2.5 hrs).",
        evening: "Overnight bus or onward travel.",
        stay: "—",
        tip: "Book the return Volvo from Bhuntar in advance on weekends.",
        stops: [{ name: "Tosh", lat: 32.016, lng: 77.452 }],
      },
    ],
  },
];
