import type { Destination } from "../types";

// Seed content. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const north: Destination[] = [
  {
    slug: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    tagline: "The old summer capital",
    summary:
      "The British-era summer capital: Mall Road walks, a UNESCO toy train and pine-forest day trips.",
    tourType: "hills",
    lat: 31.1048,
    lng: 77.1734,
    bestTime: {
      months: "Mar – Jun, Oct – Dec",
      note: "Mild days in spring and crisp, clear autumns. Snow usually falls late Dec–Feb; Jul–Aug brings landslides.",
    },
    bestMonths: [3, 4, 5, 6, 10, 11, 12],
    howToReach:
      "Fly to Chandigarh, then 115 km (about 4 hrs) by road. Or take a train to Kalka and the toy train up (5–6 hrs). Shimla airport has only a few small flights.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "2,276 m" },
      { label: "Landscape", value: "Pine ridges" },
      { label: "Best time", value: "Mar–Jun" },
      { label: "Famous for", value: "Toy train" },
    ],
    experiences: [
      { name: "Kalka–Shimla toy train", duration: "5–6 hrs", icon: "train" },
      { name: "Jakhu Temple walk", duration: "2 hrs", icon: "temple" },
      { name: "Lakkar Bazaar shopping", duration: "1–2 hrs", icon: "shopping" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and walk the Ridge",
        morning: "Drive up from Chandigarh or Kalka through Solan.",
        afternoon: "Check in and rest. Most of central Shimla is pedestrian-only, so expect to walk with bags.",
        evening: "The Ridge, Christ Church and Scandal Point, then dinner along Mall Road.",
        stay: "Near Mall Road",
        tip: "Hotels near the Mall are uphill from the parking areas; ask about porters or the lift from Cart Road.",
        stops: [
          { name: "The Ridge", lat: 31.1045, lng: 77.1734 },
          { name: "Christ Church", lat: 31.1044, lng: 77.1751 },
        ],
      },
      {
        title: "Jakhu Hill and Viceregal Lodge",
        morning: "Walk up to Jakhu Temple and its giant Hanuman statue, or take the ropeway.",
        afternoon: "Viceregal Lodge (now the Indian Institute of Advanced Study): guided tour of the building and lawns.",
        evening: "Browse woodcraft in Lakkar Bazaar.",
        stay: "Near Mall Road",
        tip: "Monkeys at Jakhu grab glasses, phones and food. Keep them in a closed bag.",
        stops: [
          { name: "Jakhu Temple", lat: 31.101, lng: 77.184 },
          { name: "Viceregal Lodge", lat: 31.1035, lng: 77.141 },
          { name: "Lakkar Bazaar", lat: 31.106, lng: 77.176 },
        ],
      },
      {
        title: "Kufri and Mashobra",
        morning: "Drive 16 km to Kufri for valley views and pony rides to the upper viewpoint.",
        afternoon: "Quiet forest walks around Mashobra.",
        evening: "Back to Shimla for dinner.",
        stay: "Near Mall Road",
        tip: "Agree on pony rates at Kufri before you start; the trail gets very muddy after rain.",
        stops: [
          { name: "Kufri", lat: 31.098, lng: 77.267 },
          { name: "Mashobra", lat: 31.13, lng: 77.229 },
        ],
      },
      {
        title: "Day trip to Chail",
        morning: "Drive about 2 hrs to Chail through deodar forest.",
        afternoon: "Chail Palace grounds and the cricket ground, said to be the highest in the world.",
        evening: "Return to Shimla.",
        stay: "Near Mall Road",
        stops: [{ name: "Chail Palace", lat: 30.966, lng: 77.199 }],
      },
      {
        title: "Narkanda and apple country",
        morning: "Drive about 2.5 hrs to Narkanda on the Hindustan–Tibet road.",
        afternoon: "Walk or drive up to Hatu Peak and its wooden temple; apple orchards line the road (harvest Aug–Oct).",
        evening: "Head back, or stay in Narkanda for a quieter night.",
        stay: "Shimla or Narkanda",
        tip: "Narkanda gets snow in winter; the Hatu road can close after a heavy fall.",
        stops: [{ name: "Narkanda", lat: 31.258, lng: 77.458 }],
      },
      {
        title: "Toy train down and depart",
        morning: "Take the morning toy train from Shimla station down to Kalka.",
        afternoon: "Connect to your onward train at Kalka or drive to Chandigarh airport (about 1 hr).",
        evening: "Departure.",
        stay: "—",
        tip: "Book toy train seats on IRCTC well ahead in May–Jun and Dec; they sell out.",
        stops: [
          { name: "Shimla station", lat: 31.1033, lng: 77.1595 },
          { name: "Kalka", lat: 30.838, lng: 76.939 },
        ],
      },
    ],
  },
  {
    slug: "manali",
    featured: true,
    name: "Manali",
    state: "Himachal Pradesh",
    tagline: "Gateway to the high passes",
    summary:
      "Snow peaks, apple orchards and Solang Valley, with the Atal Tunnel opening the road to Lahaul.",
    tourType: "mountain",
    lat: 32.2432,
    lng: 77.1892,
    bestTime: {
      months: "Mar – Jun, Oct – Dec",
      note: "Pleasant spring and clear autumn. Snow Dec–Feb. Avoid Jul–Aug, when landslides block the valley roads.",
    },
    bestMonths: [3, 4, 5, 6, 10, 11, 12],
    howToReach:
      "Overnight Volvo bus from Delhi (12–14 hrs) or fly to Bhuntar (KUU), 50 km away. The nearest major railhead is Chandigarh, about 300 km by road.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "2,050 m" },
      { label: "River", value: "Beas" },
      { label: "Best time", value: "Mar–Jun" },
      { label: "Famous for", value: "Solang Valley" },
    ],
    experiences: [
      { name: "Paragliding at Solang", duration: "15–20 min flight", icon: "mountain" },
      { name: "Beas river rafting", duration: "1–2 hrs", icon: "boat" },
      { name: "Old Manali café walk", duration: "2–3 hrs", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive, Hadimba and Old Manali",
        morning: "Reach Manali on the overnight bus or from Bhuntar. Check in and rest.",
        afternoon: "Hadimba Temple in the cedar forest, then walk down into Old Manali and Manu Temple.",
        evening: "Mall Road for dinner and a stroll.",
        stay: "Old Manali or near Mall Road",
        tip: "Hotels on the Old Manali side are quieter; Mall Road is easier for transport.",
        stops: [
          { name: "Hadimba Temple", lat: 32.2484, lng: 77.1806 },
          { name: "Old Manali", lat: 32.251, lng: 77.182 },
          { name: "Mall Road", lat: 32.2432, lng: 77.1892 },
        ],
      },
      {
        title: "Solang Valley and Atal Tunnel",
        morning: "Drive 14 km to Solang Valley for paragliding, the ropeway or snow play in winter.",
        afternoon: "Through the 9 km Atal Tunnel to Sissu in Lahaul for the waterfall and river views.",
        evening: "Back to Manali before dark.",
        stay: "Old Manali or near Mall Road",
        tip: "Rohtang Pass (open roughly May–Nov) needs an online vehicle permit and is usually shut on Tuesdays. Atal Tunnel needs no permit.",
        stops: [
          { name: "Solang Valley", lat: 32.3165, lng: 77.1572 },
          { name: "Sissu", lat: 32.48, lng: 77.125 },
        ],
      },
      {
        title: "Vashisht and Jogini Falls",
        morning: "Vashisht village and its hot spring baths.",
        afternoon: "Walk about 2.5 km uphill through orchards to Jogini Falls.",
        evening: "Café dinner in Old Manali.",
        stay: "Old Manali or near Mall Road",
        stops: [
          { name: "Vashisht", lat: 32.2659, lng: 77.1885 },
          { name: "Jogini Falls", lat: 32.272, lng: 77.195 },
        ],
      },
      {
        title: "Naggar Castle and Roerich estate",
        morning: "Drive 20 km down the left bank of the Beas to Naggar Castle.",
        afternoon: "Roerich art gallery and the painter's old house among deodars.",
        evening: "Return to Manali.",
        stay: "Old Manali or near Mall Road",
        stops: [
          { name: "Naggar Castle", lat: 32.1166, lng: 77.1667 },
          { name: "Roerich Art Gallery", lat: 32.1213, lng: 77.1716 },
        ],
      },
      {
        title: "Kasol and Manikaran",
        morning: "Drive about 3 hrs into the Parvati valley.",
        afternoon: "Manikaran gurudwara and hot springs, then riverside walks in Kasol.",
        evening: "Stay in Kasol, or drive back late.",
        stay: "Kasol",
        stops: [
          { name: "Manikaran", lat: 32.0268, lng: 77.3482 },
          { name: "Kasol", lat: 32.0099, lng: 77.3149 },
        ],
      },
      {
        title: "Kullu and depart",
        morning: "Rafting on the Beas near Kullu (season roughly Mar–Jun and Sep–Oct), or shop for Kullu shawls.",
        afternoon: "Head to Bhuntar airport or board the evening bus to Delhi.",
        evening: "Departure.",
        stay: "—",
        tip: "Flights out of Bhuntar are often cancelled in bad weather; keep a buffer day if you have a connection.",
        stops: [
          { name: "Kullu", lat: 31.958, lng: 77.11 },
          { name: "Bhuntar airport", lat: 31.8763, lng: 77.1544 },
        ],
      },
    ],
  },
  {
    slug: "leh-ladakh",
    featured: true,
    name: "Leh Ladakh",
    state: "Ladakh",
    tagline: "Land of high passes",
    summary:
      "A high-altitude desert of monasteries, Pangong's blue water and Nubra's dunes over Khardung La.",
    tourType: "mountain",
    lat: 34.1526,
    lng: 77.5771,
    bestTime: {
      months: "May – Sep",
      note: "Both road routes are usually open Jun–Sep. Winters fall well below –15 °C, though flights run all year.",
    },
    bestMonths: [5, 6, 7, 8, 9],
    howToReach:
      "Fly to Leh (IXL) from Delhi and other cities. By road: Manali–Leh (about 430 km, 2 days, roughly Jun–Oct) or Srinagar–Leh via Kargil (about 420 km, roughly May–Nov).",
    budgetPerDay: { budget: "₹2,500–4,000", mid: "₹6,000–10,000", premium: "₹15,000+" },
    facts: [
      { label: "Altitude", value: "3,500 m" },
      { label: "Landscape", value: "High desert" },
      { label: "Best time", value: "May–Sep" },
      { label: "Famous for", value: "Pangong Tso" },
    ],
    experiences: [
      { name: "Thiksey morning prayers", duration: "1–2 hrs", icon: "temple" },
      { name: "Bactrian camel ride, Hunder", duration: "1 hr", icon: "camel" },
      { name: "Motorbike ride over Khardung La", duration: "Full day", icon: "bike" },
    ],
    minDays: 4,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and rest",
        morning: "Land in Leh and go straight to your hotel.",
        afternoon: "Rest fully. Drink plenty of water, avoid alcohol and do not climb stairs or hills.",
        evening: "If you feel fine, a slow short walk around Leh market.",
        stay: "Leh",
        tip: "Leh is at 3,500 m. Take a full day of rest after flying in. Headache, nausea or breathlessness at rest are signs of AMS: tell your hotel and see a doctor; do not go higher.",
        stops: [{ name: "Leh market", lat: 34.1642, lng: 77.5848 }],
      },
      {
        title: "Leh town at an easy pace",
        morning: "Leh Palace and the view over the old town.",
        afternoon: "Hall of Fame army museum, then a drive to Gurudwara Pathar Sahib and Magnetic Hill.",
        evening: "Sunset at Shanti Stupa (drive up rather than climb the steps).",
        stay: "Leh",
        tip: "Apply now for the protected-area permit for Nubra and Pangong on the official Leh district portal, and carry several ID photocopies for checkposts.",
        stops: [
          { name: "Leh Palace", lat: 34.165, lng: 77.5847 },
          { name: "Hall of Fame", lat: 34.138, lng: 77.556 },
          { name: "Shanti Stupa", lat: 34.1736, lng: 77.5762 },
        ],
      },
      {
        title: "Indus valley monasteries",
        morning: "Early start for the morning prayer at Thiksey Monastery.",
        afternoon: "Shey Palace, then Hemis, the largest monastery in Ladakh.",
        evening: "Rest in Leh before the high passes.",
        stay: "Leh",
        tip: "The Hemis festival with masked dances falls in Jun or Jul; hotels fill up that week.",
        stops: [
          { name: "Thiksey Monastery", lat: 34.057, lng: 77.667 },
          { name: "Shey Palace", lat: 34.0727, lng: 77.638 },
          { name: "Hemis Monastery", lat: 33.9123, lng: 77.703 },
        ],
      },
      {
        title: "Pangong Tso via Chang La",
        morning: "Leave by 6 am and cross Chang La, about 5 hrs to the lake.",
        afternoon: "Pangong's shore, with the water shifting from blue to green through the day.",
        evening: "Stay in a lakeside camp, or drive back to Leh (a long 10–11 hr day).",
        stay: "Pangong camp or Leh",
        tip: "Nights at Pangong are freezing even in summer. Do not linger at Chang La; spend 15 minutes at most at the top.",
        stops: [
          { name: "Chang La", lat: 34.048, lng: 77.931 },
          { name: "Pangong Tso", lat: 33.95, lng: 78.42 },
        ],
      },
      {
        title: "Khardung La to Nubra",
        morning: "Drive over Khardung La into the Nubra valley.",
        afternoon: "Diskit Monastery and its large Maitreya Buddha statue.",
        evening: "Sand dunes at Hunder and a ride on the double-humped camels.",
        stay: "Hunder or Diskit",
        tip: "Fill fuel in Leh; pumps in Nubra are few. Prepaid SIMs from outside Ladakh do not work here; carry a postpaid connection.",
        stops: [
          { name: "Khardung La", lat: 34.2785, lng: 77.6047 },
          { name: "Diskit Monastery", lat: 34.5402, lng: 77.56 },
          { name: "Hunder dunes", lat: 34.583, lng: 77.475 },
        ],
      },
      {
        title: "Back to Leh and depart",
        morning: "Drive back over Khardung La to Leh (about 5 hrs).",
        afternoon: "Pick up pashmina, apricot jam or prayer flags in Leh market.",
        evening: "Last night in Leh; most flights out leave in the morning.",
        stay: "Leh",
        tip: "Afternoon winds can delay Leh flights, so book an early flight out and keep some slack before any connection.",
        stops: [{ name: "Leh market", lat: 34.1642, lng: 77.5848 }],
      },
    ],
  },
  {
    slug: "spiti-valley",
    name: "Spiti Valley",
    state: "Himachal Pradesh",
    tagline: "The middle land",
    summary:
      "A cold desert of cliff-top monasteries, fossil villages and some of India's highest homes.",
    tourType: "mountain",
    lat: 32.226,
    lng: 78.072,
    bestTime: {
      months: "Jun – Sep",
      note: "The Manali side over Kunzum Pass is usually open Jun–Oct. The Kinnaur route stays open most of the year, but winter is harsh.",
    },
    bestMonths: [6, 7, 8, 9],
    howToReach:
      "From Shimla via Kinnaur (about 420 km, 2 days) or from Manali via Atal Tunnel and Kunzum Pass (about 200 km, 8–10 hrs, seasonal). Nearest airports: Bhuntar and Shimla.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹3,500–6,000", premium: "₹9,000+" },
    facts: [
      { label: "Altitude (Kaza)", value: "3,800 m" },
      { label: "Landscape", value: "Cold desert" },
      { label: "Best time", value: "Jun–Sep" },
      { label: "Famous for", value: "Key Monastery" },
    ],
    experiences: [
      { name: "Key Monastery visit", duration: "2 hrs", icon: "temple" },
      { name: "Fossil walk at Langza", duration: "2 hrs", icon: "hike" },
      { name: "Camping at Chandratal", duration: "Overnight", icon: "tent" },
    ],
    minDays: 4,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive in Kaza and rest",
        morning: "Reach Kaza, the main town of Spiti.",
        afternoon: "Rest fully and drink plenty of water. No hikes today.",
        evening: "A slow walk through Kaza market if you feel fine.",
        stay: "Kaza",
        tip: "Kaza is at about 3,800 m. Headache or nausea at rest can be AMS: rest, do not go higher, and see the Kaza hospital if it gets worse.",
        stops: [{ name: "Kaza", lat: 32.227, lng: 78.071 }],
      },
      {
        title: "Key, Kibber and Chicham",
        morning: "Key Monastery on its hilltop, about 14 km from Kaza.",
        afternoon: "Kibber village, then the Chicham bridge across a deep gorge.",
        evening: "Back in Kaza.",
        stay: "Kaza",
        stops: [
          { name: "Key Monastery", lat: 32.2978, lng: 78.0119 },
          { name: "Kibber", lat: 32.333, lng: 78.009 },
          { name: "Chicham bridge", lat: 32.342, lng: 78.025 },
        ],
      },
      {
        title: "Langza, Hikkim and Komic",
        morning: "Langza and its big Buddha statue; look for marine fossils on the slopes.",
        afternoon: "Post a card from Hikkim, one of the world's highest post offices, then Komic village.",
        evening: "Back in Kaza.",
        stay: "Kaza",
        tip: "Look at fossils but leave them where they are; removing them is discouraged and villagers object.",
        stops: [
          { name: "Langza", lat: 32.2697, lng: 78.0814 },
          { name: "Hikkim", lat: 32.25, lng: 78.095 },
          { name: "Komic", lat: 32.245, lng: 78.112 },
        ],
      },
      {
        title: "Dhankar and Pin Valley",
        morning: "Dhankar Monastery on its cliff; walk up about 1 hr to Dhankar Lake if you are acclimatised.",
        afternoon: "Pin Valley to Mudh village, a base for spotting ibex.",
        evening: "Stay in a Mudh homestay or return to Kaza.",
        stay: "Mudh or Kaza",
        stops: [
          { name: "Dhankar Monastery", lat: 32.0874, lng: 78.2186 },
          { name: "Mudh", lat: 31.96, lng: 78.03 },
        ],
      },
      {
        title: "Tabo",
        morning: "Drive to Tabo (about 1.5 hrs from Kaza).",
        afternoon: "Tabo Monastery, founded in 996, with its old murals, and the meditation caves above the village.",
        evening: "Return to Kaza, or stay in Tabo if leaving via Kinnaur.",
        stay: "Kaza or Tabo",
        tip: "Foreign nationals need an Inner Line Permit for the Kinnaur border stretch; Indian citizens only need ID at checkposts.",
        stops: [{ name: "Tabo Monastery", lat: 32.093, lng: 78.383 }],
      },
      {
        title: "Chandratal and exit to Manali",
        morning: "Leave early over Kunzum Pass (open roughly Jun–Oct).",
        afternoon: "Detour to Chandratal lake, then continue via Batal and the Atal Tunnel.",
        evening: "Reach Manali late, or camp at Chandratal.",
        stay: "Manali or Chandratal camp",
        tip: "The Losar–Batal road is rough with stream crossings. Cross them in the morning, before snowmelt raises the water.",
        stops: [
          { name: "Kunzum Pass", lat: 32.397, lng: 77.637 },
          { name: "Chandratal", lat: 32.475, lng: 77.617 },
        ],
      },
    ],
  },
  {
    slug: "gulmarg",
    name: "Gulmarg",
    state: "Jammu & Kashmir",
    tagline: "Meadow of flowers",
    summary: "Kashmir's ski slopes and alpine meadow, with one of the world's highest cable cars.",
    tourType: "snow",
    lat: 34.0484,
    lng: 74.3805,
    bestTime: {
      months: "Dec – Mar, May – Jun",
      note: "Deep snow and skiing in winter; green meadows and wildflowers in early summer.",
    },
    bestMonths: [12, 1, 2, 3, 5, 6],
    howToReach:
      "Fly or take the train to Srinagar, then drive about 50 km (1.5–2 hrs) via Tangmarg. Taxis from Srinagar are the usual option.",
    budgetPerDay: { budget: "₹2,500–4,000", mid: "₹6,000–10,000", premium: "₹18,000+" },
    facts: [
      { label: "Altitude", value: "2,650 m" },
      { label: "Gondola top", value: "3,980 m" },
      { label: "Ski season", value: "Dec–Mar" },
      { label: "From Srinagar", value: "50 km" },
    ],
    experiences: [
      { name: "Gulmarg Gondola", duration: "2–4 hrs", icon: "mountain" },
      { name: "Beginner ski lesson", duration: "Half day", icon: "ski" },
      { name: "Shikara on Dal Lake", duration: "1–2 hrs", icon: "boat" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and walk the meadow",
        morning: "Reach Srinagar and drive up to Gulmarg via Tangmarg.",
        afternoon: "Walk the meadow to the Maharani Temple and St Mary's Church.",
        evening: "Early night; temperatures drop fast after sunset.",
        stay: "Gulmarg",
        tip: "After heavy snow, cars need chains or 4x4 beyond Tangmarg. Carry ID; there are security checks on the road.",
        stops: [
          { name: "Tangmarg", lat: 34.061, lng: 74.424 },
          { name: "Maharani Temple", lat: 34.053, lng: 74.383 },
        ],
      },
      {
        title: "Gondola to Kongdori and Apharwat",
        morning: "First gondola up to Kongdori (Phase 1).",
        afternoon: "Phase 2 to Apharwat, close to 4,000 m, if the weather allows.",
        evening: "Back down for a warm dinner.",
        stay: "Gulmarg",
        tip: "Buy gondola tickets online on the official J&K Cable Car site days ahead. Phase 2 shuts in high wind, so go early.",
        stops: [
          { name: "Gondola base", lat: 34.046, lng: 74.379 },
          { name: "Kongdori", lat: 34.033, lng: 74.37 },
        ],
      },
      {
        title: "Snow day or Khilanmarg",
        morning: "Winter: a beginner ski lesson with a certified instructor. Summer: walk to Khilanmarg (about 6 km round trip).",
        afternoon: "Sledging or snow play near the base; in summer, pony rides around the meadow.",
        evening: "Rest; Gulmarg has little nightlife.",
        stay: "Gulmarg",
        tip: "Hire ski gear and instructors from the government ski shop or registered outfits, and fix the price first.",
        stops: [{ name: "Khilanmarg", lat: 34.061, lng: 74.357 }],
      },
      {
        title: "Srinagar and Dal Lake",
        morning: "Drive down to Srinagar.",
        afternoon: "Check in to a houseboat on Dal or Nigeen Lake.",
        evening: "Shikara ride on the lake at sunset.",
        stay: "Houseboat, Srinagar",
        tip: "Agree on the shikara rate per hour before you board.",
        stops: [{ name: "Dal Lake", lat: 34.115, lng: 74.86 }],
      },
      {
        title: "Mughal gardens",
        morning: "Nishat Bagh, then Shalimar Bagh along the lake.",
        afternoon: "Pari Mahal for views over Dal Lake.",
        evening: "Kashmiri wazwan dinner in the city.",
        stay: "Houseboat, Srinagar",
        tip: "Gardens are at their best in Apr–May when the tulips and roses bloom.",
        stops: [
          { name: "Nishat Bagh", lat: 34.1253, lng: 74.88 },
          { name: "Shalimar Bagh", lat: 34.149, lng: 74.873 },
          { name: "Pari Mahal", lat: 34.0915, lng: 74.8785 },
        ],
      },
      {
        title: "Old city and depart",
        morning: "Hazratbal shrine on the lake, then Jamia Masjid in the old city.",
        afternoon: "Head to Srinagar airport or station.",
        evening: "Departure.",
        stay: "—",
        tip: "Srinagar airport has several security checks before the terminal; arrive at least 2.5 hrs early.",
        stops: [
          { name: "Hazratbal", lat: 34.1288, lng: 74.8424 },
          { name: "Jamia Masjid", lat: 34.099, lng: 74.8103 },
        ],
      },
    ],
  },
  {
    slug: "auli",
    name: "Auli",
    state: "Uttarakhand",
    tagline: "Skiing under Nanda Devi",
    summary:
      "Uttarakhand's ski slopes and oak-forest meadows facing Nanda Devi, just above Joshimath.",
    tourType: "snow",
    lat: 30.528,
    lng: 79.566,
    bestTime: {
      months: "Dec – Mar, Apr – Jun",
      note: "Snow and skiing usually Jan–Mar; green slopes and clear peaks in spring. Avoid Jul–Sep for landslides.",
    },
    bestMonths: [12, 1, 2, 3, 4, 5, 6],
    howToReach:
      "Drive from Rishikesh or Haridwar (about 250 km, 9–10 hrs) to Joshimath, then 16 km up to Auli. Nearest airport: Dehradun (Jolly Grant).",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹10,000+" },
    facts: [
      { label: "Altitude", value: "2,800 m" },
      { label: "Ski season", value: "Jan–Mar" },
      { label: "Peak view", value: "Nanda Devi" },
      { label: "Nearest town", value: "Joshimath" },
    ],
    experiences: [
      { name: "Beginner ski course", duration: "Half day", icon: "ski" },
      { name: "Gorson Bugyal hike", duration: "3–4 hrs", icon: "hike" },
      { name: "Nanda Devi sunrise", duration: "1 hr", icon: "sunrise" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Up the Alaknanda to Auli",
        morning: "Drive the last stretch up the Alaknanda valley to Joshimath.",
        afternoon: "Take the 16 km road up to Auli and check in.",
        evening: "Rest; you have climbed a long way in two days.",
        stay: "Auli",
        tip: "Most people break the drive from Rishikesh at Rudraprayag or Srinagar (Garhwal). Do not drive these roads after dark.",
        stops: [
          { name: "Joshimath", lat: 30.556, lng: 79.565 },
          { name: "Auli", lat: 30.528, lng: 79.566 },
        ],
      },
      {
        title: "Slopes and chairlift",
        morning: "Watch sunrise over Nanda Devi from the slopes.",
        afternoon: "Chairlift up the slope, or a beginner ski lesson in season.",
        evening: "Walk to the artificial lake viewpoint near the top of the slope.",
        stay: "Auli",
        tip: "Check whether the Joshimath–Auli ropeway is running; it has been shut for long spells since 2023.",
        stops: [{ name: "Auli slopes", lat: 30.528, lng: 79.566 }],
      },
      {
        title: "Gorson Bugyal",
        morning: "Hike about 3 km through oak and conifer forest to the Gorson Bugyal meadow.",
        afternoon: "Picnic with views of Trishul and Nanda Devi, then walk back.",
        evening: "Quiet evening in Auli.",
        stay: "Auli",
        tip: "Go with a local guide in snow; the trail markers get buried.",
        stops: [{ name: "Gorson Bugyal", lat: 30.515, lng: 79.585 }],
      },
      {
        title: "Badrinath and Mana",
        morning: "Drive about 2 hrs to Badrinath Temple (open roughly May–Nov).",
        afternoon: "Mana village near the Tibet border and Bhim Pul.",
        evening: "Return to Auli. In winter, swap this for a Joshimath temple day.",
        stay: "Auli",
        tip: "Carry ID; there are checkposts on this road. Landslides can close it for hours, so start early.",
        stops: [
          { name: "Badrinath Temple", lat: 30.7446, lng: 79.4932 },
          { name: "Mana", lat: 30.772, lng: 79.496 },
        ],
      },
      {
        title: "Joshimath and Vishnuprayag",
        morning: "Narsingh Temple in Joshimath, the winter seat of Badrinath.",
        afternoon: "Vishnuprayag, where the Dhauliganga meets the Alaknanda.",
        evening: "Pack for an early start.",
        stay: "Auli or Joshimath",
        tip: "Parts of Joshimath have land subsidence; follow local advisories on which areas to avoid.",
        stops: [
          { name: "Narsingh Temple", lat: 30.5545, lng: 79.564 },
          { name: "Vishnuprayag", lat: 30.566, lng: 79.575 },
        ],
      },
      {
        title: "Down to Rishikesh",
        morning: "Leave by 6 am for the long drive down.",
        afternoon: "Stop at the Rudraprayag and Devprayag confluences on the way.",
        evening: "Reach Rishikesh or Haridwar for your onward train or flight.",
        stay: "—",
        tip: "Allow 9–10 hrs to Rishikesh; book onward travel for the next day if you can.",
        stops: [
          { name: "Rudraprayag", lat: 30.2844, lng: 78.9811 },
          { name: "Devprayag", lat: 30.1458, lng: 78.5984 },
        ],
      },
    ],
  },
];
