import type { Destination } from "../types";

// Seed content for South India. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const south: Destination[] = [
  {
    slug: "munnar",
    featured: true,
    name: "Munnar",
    state: "Kerala",
    tagline: "Tea country of Kerala",
    summary: "Rolling tea estates, misty Western Ghats viewpoints and Nilgiri tahr at Eravikulam National Park.",
    tourType: "hills",
    lat: 10.0889,
    lng: 77.0595,
    bestTime: {
      months: "Sep – May",
      note: "Cool and clear Sep–Mar. Jun–Aug brings heavy monsoon rain and occasional landslides on the ghat roads.",
    },
    bestMonths: [9, 10, 11, 12, 1, 2, 3, 4, 5],
    howToReach:
      "Fly to Kochi (COK), about 110 km and 4 hrs by road. Nearest major stations are Aluva and Ernakulam. Madurai airport is about 4.5 hrs on the Tamil Nadu side.",
    budgetPerDay: { budget: "₹1,800–3,000", mid: "₹4,500–8,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "About 1,600 m" },
      { label: "Landscape", value: "Tea hills" },
      { label: "Best time", value: "Sep–Mar" },
      { label: "Famous for", value: "Nilgiri tahr" },
    ],
    experiences: [
      { name: "Eravikulam park visit", duration: "3 hrs", icon: "binoculars" },
      { name: "Tea museum and estate walk", duration: "2–3 hrs", icon: "leaf" },
      { name: "Kolukkumalai sunrise jeep", duration: "4 hrs", icon: "sunrise" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive through the ghats",
        morning: "Drive up from Kochi on the NH85, past Cheeyappara and Valara waterfalls.",
        afternoon: "Check in, then visit the Tata Tea Museum to see how the leaf is processed.",
        evening: "Walk around Munnar town and pick up fresh tea and spices.",
        stay: "Munnar town or nearby estates",
        tip: "The Tea Museum is closed on Mondays. The ghat drive is slow; plan 4 hrs from Kochi.",
        stops: [
          { name: "Tata Tea Museum", lat: 10.0961, lng: 77.0603 },
          { name: "Munnar town", lat: 10.0889, lng: 77.0595 },
        ],
      },
      {
        title: "Eravikulam National Park",
        morning: "Reach Rajamalai early for the forest bus into Eravikulam. Look for Nilgiri tahr on the grassy slopes below Anamudi.",
        afternoon: "Short walk through the tea estates along the Rajamalai road.",
        evening: "Sunset over the tea slopes, then an early night.",
        stay: "Munnar town or nearby estates",
        tip: "The park usually closes Feb–Mar for the tahr calving season. Book tickets online and go before 9 am to beat the queue.",
        stops: [{ name: "Eravikulam (Rajamalai)", lat: 10.18, lng: 77.06 }],
      },
      {
        title: "Top Station road",
        morning: "Mattupetty Dam and a stop at Echo Point.",
        afternoon: "Kundala Lake, then on to Top Station for views down into Tamil Nadu.",
        evening: "Head back before dark; the road has few lights.",
        stay: "Munnar town or nearby estates",
        tip: "Mist often rolls in at Top Station after noon. Go early in the day if the sky is clear.",
        stops: [
          { name: "Mattupetty Dam", lat: 10.1063, lng: 77.1236 },
          { name: "Kundala Lake", lat: 10.143, lng: 77.198 },
          { name: "Top Station", lat: 10.1257, lng: 77.2437 },
        ],
      },
      {
        title: "Day trip to Marayoor",
        morning: "Drive about 1.5 hrs north, past Eravikulam, to Marayoor.",
        afternoon: "Government sandalwood forest, the ancient dolmens and a traditional jaggery unit.",
        evening: "Return to Munnar.",
        stay: "Munnar town or nearby estates",
        tip: "Marayoor jaggery has a GI tag. Buy it from the units directly.",
        stops: [{ name: "Marayoor", lat: 10.2765, lng: 77.1636 }],
      },
      {
        title: "Kolukkumalai sunrise",
        morning: "Leave around 4 am for Suryanelli and take a jeep up to Kolukkumalai, one of the highest tea estates in the world, for sunrise.",
        afternoon: "Rest after the early start, or visit a spice garden near town.",
        evening: "Kathakali or Kalaripayattu show in town.",
        stay: "Munnar town or nearby estates",
        tip: "Private cars cannot go up the last stretch. Book the jeep from Suryanelli the day before.",
        stops: [{ name: "Kolukkumalai", lat: 10.073, lng: 77.226 }],
      },
      {
        title: "Spice garden and depart",
        morning: "Spice plantation walk near Adimali on the way down.",
        afternoon: "Continue to Kochi for your flight or train.",
        evening: "Departure.",
        stay: "—",
        tip: "Keep 4–5 hrs for the drive to Kochi airport.",
        stops: [{ name: "Adimali", lat: 10.013, lng: 76.95 }],
      },
    ],
  },
  {
    slug: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    tagline: "Queen of the Nilgiris",
    summary: "The Nilgiri toy train, colonial gardens and eucalyptus hills high in the Western Ghats.",
    tourType: "hills",
    lat: 11.4102,
    lng: 76.695,
    bestTime: {
      months: "Oct – Jun",
      note: "Apr–May is peak season and crowded. Dec–Feb nights can drop near freezing. Jul–Aug is wet.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3, 4, 5, 6],
    howToReach:
      "Fly to Coimbatore (CJB), about 3 hrs by road. Or take a train to Mettupalayam and ride the Nilgiri Mountain Railway up to Ooty.",
    budgetPerDay: { budget: "₹1,800–3,000", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Altitude", value: "2,240 m" },
      { label: "Landscape", value: "Nilgiri hills" },
      { label: "Best time", value: "Oct–Jun" },
      { label: "Famous for", value: "Toy train" },
    ],
    experiences: [
      { name: "Nilgiri toy train", duration: "1–5 hrs", icon: "train" },
      { name: "Doddabetta peak", duration: "2 hrs", icon: "mountain" },
      { name: "Ooty Lake boating", duration: "1 hr", icon: "boat" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Arrive and the lake",
        morning: "Drive up from Coimbatore through the Mettupalayam ghat.",
        afternoon: "Check in, then a boat ride on Ooty Lake.",
        evening: "Charing Cross and the market area; try homemade chocolates and varkey.",
        stay: "Near Charing Cross",
        tip: "Check whether the Nilgiris e-pass for visiting vehicles is in force before you travel. Single-use plastic bottles are banned in the district.",
        stops: [{ name: "Ooty Lake", lat: 11.4053, lng: 76.6879 }],
      },
      {
        title: "Gardens and Doddabetta",
        morning: "Government Botanical Garden, then the Rose Garden on Elk Hill.",
        afternoon: "Doddabetta, the highest point in the Nilgiris, and a tea factory visit on the way down.",
        evening: "Warm dinner and an early night.",
        stay: "Near Charing Cross",
        tip: "Reach Doddabetta before noon; clouds usually cover the view later.",
        stops: [
          { name: "Botanical Garden", lat: 11.4183, lng: 76.711 },
          { name: "Rose Garden", lat: 11.4063, lng: 76.7106 },
          { name: "Doddabetta Peak", lat: 11.4012, lng: 76.736 },
        ],
      },
      {
        title: "Toy train to Coonoor",
        morning: "Ride the Nilgiri Mountain Railway from Ooty down to Coonoor.",
        afternoon: "Sim's Park and the viewpoints at Lamb's Rock and Dolphin's Nose.",
        evening: "Return to Ooty by road.",
        stay: "Near Charing Cross",
        tip: "Seats sell out weeks ahead in season. Book on IRCTC as soon as reservations open.",
        stops: [
          { name: "Ooty station", lat: 11.404, lng: 76.696 },
          { name: "Sim's Park, Coonoor", lat: 11.3638, lng: 76.807 },
        ],
      },
      {
        title: "Pine forest and Pykara",
        morning: "Walk in the pine forest on the Pykara road.",
        afternoon: "Pykara Falls and a boat ride on Pykara Lake.",
        evening: "Back to Ooty for dinner.",
        stay: "Near Charing Cross",
        stops: [{ name: "Pykara Falls", lat: 11.457, lng: 76.604 }],
      },
      {
        title: "Mudumalai",
        morning: "Drive down the Kalhatti ghat to Theppakadu in Mudumalai Tiger Reserve.",
        afternoon: "Forest department safari and the elephant camp.",
        evening: "Return to Ooty, or stay at Masinagudi.",
        stay: "Ooty or Masinagudi",
        tip: "The Kalhatti ghat has 36 hairpin bends and is very steep. Use low gear and avoid driving it after dark.",
        stops: [{ name: "Theppakadu", lat: 11.578, lng: 76.582 }],
      },
      {
        title: "Tea shopping and depart",
        morning: "Buy Nilgiri tea, eucalyptus oil and chocolates in town.",
        afternoon: "Drive to Coimbatore, or take the afternoon toy train down to Mettupalayam.",
        evening: "Departure.",
        stay: "—",
        tip: "Allow 3–4 hrs to Coimbatore airport; weekend traffic on the ghat is slow.",
        stops: [{ name: "Charing Cross", lat: 11.4119, lng: 76.7036 }],
      },
    ],
  },
  {
    slug: "alleppey",
    featured: true,
    name: "Alleppey",
    state: "Kerala",
    tagline: "Houseboats on the backwaters",
    summary: "A night on a houseboat, palm-lined canals and paddy fields that sit below sea level in Kuttanad.",
    tourType: "backwaters",
    lat: 9.4981,
    lng: 76.3388,
    bestTime: {
      months: "Oct – Mar",
      note: "Pleasant and dry. Migratory birds at Kumarakom Nov–Feb. Monsoon (Jun–Sep) is lush but wet.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Kochi (COK), about 85 km and 2 hrs by road. Alappuzha station is on the coastal line from Ernakulam and Thiruvananthapuram.",
    budgetPerDay: { budget: "₹2,000–3,500", mid: "₹6,000–10,000", premium: "₹15,000+" },
    facts: [
      { label: "Landscape", value: "Backwaters" },
      { label: "Lake", value: "Vembanad" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Houseboats" },
    ],
    experiences: [
      { name: "Overnight houseboat", duration: "22 hrs", icon: "boat" },
      { name: "Canoe through canals", duration: "3 hrs", icon: "waves" },
      { name: "Kerala meals and karimeen", duration: "1 hr", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Houseboat night",
        morning: "Arrive in Alappuzha and board your houseboat around noon near Punnamada.",
        afternoon: "Cruise through Vembanad Lake and the Kuttanad canals; lunch is cooked on board.",
        evening: "The boat anchors for the night in a quiet stretch. Tea and snacks on deck at sunset.",
        stay: "Houseboat",
        tip: "Boats must stop cruising around 5:30 pm and anchor overnight. Book a licensed boat and confirm whether AC runs all night or only after dark.",
        stops: [{ name: "Punnamada houseboat point", lat: 9.506, lng: 76.343 }],
      },
      {
        title: "Canals and the beach",
        morning: "Breakfast on board and check out around 9 am. Take a small canoe into narrow canals the big boats cannot enter.",
        afternoon: "Check in to a homestay and rest.",
        evening: "Alappuzha Beach and the old pier at sunset.",
        stay: "Homestay in Alappuzha",
        tip: "Ask the canoe operator to stop at a toddy shop or a village tea stall.",
        stops: [{ name: "Alappuzha Beach", lat: 9.4932, lng: 76.3172 }],
      },
      {
        title: "Marari Beach",
        morning: "Drive 30 minutes north to Marari, a quiet fishing-village beach.",
        afternoon: "Watch the fishing boats come in; lunch on fresh seafood.",
        evening: "Sunset on the beach, then back to Alappuzha.",
        stay: "Alappuzha or Marari",
        tip: "Currents can be strong. Swim only where locals do and stay close to shore.",
        stops: [{ name: "Marari Beach", lat: 9.6007, lng: 76.2984 }],
      },
      {
        title: "Day trip to Kumarakom",
        morning: "Drive about 1 hr to Kumarakom Bird Sanctuary on the east side of Vembanad Lake. Go at dawn for the birds.",
        afternoon: "Boat across the lake to Pathiramanal island.",
        evening: "Return to Alappuzha.",
        stay: "Homestay in Alappuzha",
        tip: "Bird life is best Nov–Feb. Carry binoculars and insect repellent.",
        stops: [
          { name: "Kumarakom Bird Sanctuary", lat: 9.6253, lng: 76.4285 },
          { name: "Pathiramanal", lat: 9.62, lng: 76.384 },
        ],
      },
      {
        title: "Ferry and Kuttanad villages",
        morning: "Ride a State Water Transport ferry from the Alappuzha jetty; cheap, slow and full of locals.",
        afternoon: "Champakulam village and its old church, then Ambalappuzha temple, known for its milk payasam.",
        evening: "Kerala meals and karimeen (pearl spot) for dinner.",
        stay: "Homestay in Alappuzha",
        tip: "Kerala temples expect traditional dress, and men may be asked to remove shirts. Entry for non-Hindus is restricted at many temples.",
        stops: [
          { name: "Alappuzha boat jetty", lat: 9.4987, lng: 76.3404 },
          { name: "Champakulam", lat: 9.41, lng: 76.41 },
          { name: "Ambalappuzha", lat: 9.383, lng: 76.361 },
        ],
      },
      {
        title: "Sunrise kayak and depart",
        morning: "Sunrise kayak on the canals before the boats start up.",
        afternoon: "Drive to Kochi for your flight or train.",
        evening: "Departure.",
        stay: "—",
        tip: "The Nehru Trophy snake boat race is held on Punnamada Lake on the second Saturday of August.",
        stops: [{ name: "Alappuzha canals", lat: 9.498, lng: 76.338 }],
      },
    ],
  },
  {
    slug: "gokarna",
    name: "Gokarna",
    state: "Karnataka",
    tagline: "Temple town, quiet beaches",
    summary: "An old temple town with a string of cliff-backed beaches linked by a coastal walking trail.",
    tourType: "beach",
    lat: 14.5479,
    lng: 74.3188,
    bestTime: {
      months: "Oct – Mar",
      note: "Calm sea and dry weather. Most beach shacks shut Jun–Sep and the sea is rough.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Take a Konkan Railway train to Gokarna Road (about 10 km) or Kumta. Goa's Dabolim airport is about 140 km, roughly 3.5 hrs by road.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹10,000+" },
    facts: [
      { label: "Landscape", value: "Cliff beaches" },
      { label: "Coast", value: "Karnataka" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Beach trek" },
    ],
    experiences: [
      { name: "Five-beach coastal trek", duration: "4–5 hrs", icon: "hike" },
      { name: "Mahabaleshwar Temple", duration: "1 hr", icon: "temple" },
      { name: "Sunset at Kudle Beach", duration: "2 hrs", icon: "waves" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Temple town",
        morning: "Arrive and check in near Kudle or in town.",
        afternoon: "Mahabaleshwar Temple and a walk down Car Street.",
        evening: "Sunset on Gokarna main beach, where pilgrims bathe.",
        stay: "Kudle Beach or Gokarna town",
        tip: "Traditional dress is expected at the temple. Men may be asked to remove shirts inside.",
        stops: [
          { name: "Mahabaleshwar Temple", lat: 14.5434, lng: 74.3168 },
          { name: "Gokarna Beach", lat: 14.547, lng: 74.314 },
        ],
      },
      {
        title: "The beach trek",
        morning: "Start early from Kudle and walk the cliff trail to Om Beach.",
        afternoon: "Continue to Half Moon and Paradise beaches; take a boat back to Om Beach.",
        evening: "Sunset and dinner at a Kudle beach café.",
        stay: "Kudle Beach or Gokarna town",
        tip: "Carry 2 litres of water and wear proper shoes; the rocks are slippery. Half Moon and Paradise have very few facilities.",
        stops: [
          { name: "Kudle Beach", lat: 14.5297, lng: 74.3175 },
          { name: "Om Beach", lat: 14.519, lng: 74.322 },
          { name: "Half Moon Beach", lat: 14.511, lng: 74.32 },
        ],
      },
      {
        title: "Mirjan Fort and Yana",
        morning: "Mirjan Fort, a moss-covered laterite fort about 25 km away.",
        afternoon: "Yana, with its two huge black limestone rock towers in the forest.",
        evening: "Return to Gokarna.",
        stay: "Kudle Beach or Gokarna town",
        tip: "The last stretch to Yana is a short walk with steps. Avoid it in heavy rain.",
        stops: [
          { name: "Mirjan Fort", lat: 14.4887, lng: 74.4196 },
          { name: "Yana", lat: 14.59, lng: 74.56 },
        ],
      },
      {
        title: "Day trip to Murudeshwar",
        morning: "Drive about 2 hrs south to Murudeshwar.",
        afternoon: "The seaside temple and its giant Shiva statue; ride the lift up the temple tower for the view.",
        evening: "Return to Gokarna.",
        stay: "Kudle Beach or Gokarna town",
        tip: "Scuba trips to Netrani Island leave from Murudeshwar, usually Oct–May. Book a day ahead.",
        stops: [{ name: "Murudeshwar", lat: 14.0943, lng: 74.4848 }],
      },
      {
        title: "Slow day on Om Beach",
        morning: "Yoga session or a slow breakfast by the sea.",
        afternoon: "Boat ride from Om Beach to look for dolphins, or kayak in the bay.",
        evening: "Sunset from the Om Beach headland.",
        stay: "Kudle Beach or Gokarna town",
        tip: "Swim only in marked areas and follow lifeguards. Drownings happen here every season.",
        stops: [{ name: "Om Beach", lat: 14.519, lng: 74.322 }],
      },
      {
        title: "Koti Teertha and depart",
        morning: "Early walk around the Koti Teertha temple tank and the old town lanes.",
        afternoon: "Head to Gokarna Road, Kumta or Goa for your onward journey.",
        evening: "Departure.",
        stay: "—",
        tip: "Few trains stop at Gokarna Road. Check the timing and book ahead.",
        stops: [{ name: "Koti Teertha", lat: 14.544, lng: 74.3185 }],
      },
    ],
  },
  {
    slug: "pondicherry",
    name: "Pondicherry",
    state: "Puducherry",
    tagline: "French Quarter by the sea",
    summary: "Yellow French-era streets, a seafront promenade, Sri Aurobindo Ashram and Auroville next door.",
    tourType: "beach",
    lat: 11.9416,
    lng: 79.8083,
    bestTime: {
      months: "Dec – Mar",
      note: "Pleasant and dry. Northeast monsoon rain peaks Oct–Nov, with a risk of cyclones. Apr–Jun is hot and humid.",
    },
    bestMonths: [12, 1, 2, 3],
    howToReach:
      "Fly to Chennai (MAA), about 150 km and 3.5 hrs down the East Coast Road. Trains run from Chennai Egmore; Villupuram is the nearest main junction.",
    budgetPerDay: { budget: "₹1,800–3,000", mid: "₹4,500–8,000", premium: "₹12,000+" },
    facts: [
      { label: "Landscape", value: "Coast" },
      { label: "Heritage", value: "French Quarter" },
      { label: "Best time", value: "Dec–Mar" },
      { label: "Famous for", value: "Auroville" },
    ],
    experiences: [
      { name: "French Quarter walk", duration: "2–3 hrs", icon: "camera" },
      { name: "Cycle to Auroville", duration: "Half day", icon: "bike" },
      { name: "Paradise Beach boat", duration: "3 hrs", icon: "boat" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "French Quarter and the Promenade",
        morning: "Arrive and check in around White Town.",
        afternoon: "Walk the French Quarter: Rue Dumas, Rue Romain Rolland and the colonial villas.",
        evening: "Stroll on Promenade Beach; the road is closed to traffic in the evening.",
        stay: "White Town",
        tip: "Rent a bicycle or scooter for the week; distances are short.",
        stops: [{ name: "Promenade Beach", lat: 11.9333, lng: 79.8365 }],
      },
      {
        title: "Ashram and temples",
        morning: "Sri Aurobindo Ashram and the Samadhi, then Manakula Vinayagar Temple nearby.",
        afternoon: "Basilica of the Sacred Heart of Jesus, then a café break.",
        evening: "Dinner at a French or Tamil restaurant in White Town.",
        stay: "White Town",
        tip: "The Ashram expects silence and modest dress. Photography is not allowed inside.",
        stops: [
          { name: "Sri Aurobindo Ashram", lat: 11.9365, lng: 79.8347 },
          { name: "Basilica of the Sacred Heart", lat: 11.928, lng: 79.826 },
        ],
      },
      {
        title: "Auroville",
        morning: "Auroville Visitors Centre, then the walk to the Matrimandir viewing point.",
        afternoon: "Lunch at a café in Auroville and browse the handmade crafts.",
        evening: "Back to town for a sunset on the Promenade.",
        stay: "White Town",
        tip: "Entry inside the Matrimandir needs a booking made in advance at the Visitors Centre. The viewing point needs only a free pass.",
        stops: [
          { name: "Auroville Visitors Centre", lat: 12.0056, lng: 79.8106 },
          { name: "Matrimandir", lat: 12.0069, lng: 79.8105 },
        ],
      },
      {
        title: "Paradise Beach and Serenity",
        morning: "Boat from Chunnambar boat house through the backwaters to Paradise Beach.",
        afternoon: "Swim and relax; shacks serve basic food.",
        evening: "Serenity Beach, north of town, for sunset. Surf lessons run here for beginners.",
        stay: "White Town",
        tip: "Take the first boats of the morning; queues build by 11 am on weekends.",
        stops: [
          { name: "Chunnambar boat house", lat: 11.883, lng: 79.814 },
          { name: "Paradise Beach", lat: 11.886, lng: 79.833 },
          { name: "Serenity Beach", lat: 11.98, lng: 79.84 },
        ],
      },
      {
        title: "Day trip to Mahabalipuram",
        morning: "Drive about 2.5 hrs north on the East Coast Road to Mahabalipuram.",
        afternoon: "Shore Temple, Arjuna's Penance and the Five Rathas, all UNESCO-listed Pallava monuments.",
        evening: "Return to Pondicherry.",
        stay: "White Town",
        tip: "One ASI ticket covers the Shore Temple and the Five Rathas. Go early; the rocks get very hot by noon.",
        stops: [
          { name: "Shore Temple", lat: 12.6164, lng: 80.1993 },
          { name: "Arjuna's Penance", lat: 12.6175, lng: 80.1918 },
          { name: "Five Rathas", lat: 12.608, lng: 80.189 },
        ],
      },
      {
        title: "Tamil Quarter and depart",
        morning: "Goubert Market and the Tamil Quarter lanes for spices, flowers and local snacks.",
        afternoon: "Head to Chennai for your flight or train.",
        evening: "Departure.",
        stay: "—",
        tip: "Allow 4 hrs to Chennai airport; traffic builds near the city.",
        stops: [{ name: "Goubert Market", lat: 11.935, lng: 79.831 }],
      },
    ],
  },
  {
    slug: "hampi",
    name: "Hampi",
    state: "Karnataka",
    tagline: "Ruins of Vijayanagara",
    summary: "The ruined Vijayanagara capital, scattered across a boulder landscape on the Tungabhadra river.",
    tourType: "heritage",
    lat: 15.335,
    lng: 76.46,
    bestTime: {
      months: "Oct – Feb",
      note: "Warm days and cool nights. Mar–May crosses 40 °C. Monsoon turns the land green but makes river crossings unsafe.",
    },
    bestMonths: [10, 11, 12, 1, 2],
    howToReach:
      "Take a train to Hosapete (Hospet), 13 km away; the overnight Hampi Express runs from Bengaluru. Nearest airports are Vijayanagar (Toranagallu) with limited flights, and Hubballi, about 3.5 hrs.",
    budgetPerDay: { budget: "₹1,200–2,000", mid: "₹3,000–5,500", premium: "₹12,000+" },
    facts: [
      { label: "UNESCO site", value: "Since 1986" },
      { label: "Landscape", value: "Boulder hills" },
      { label: "Best time", value: "Oct–Feb" },
      { label: "Famous for", value: "Stone chariot" },
    ],
    experiences: [
      { name: "Vittala Temple", duration: "2–3 hrs", icon: "temple" },
      { name: "Coracle ride", duration: "30 min", icon: "boat" },
      { name: "Cycle the ruins", duration: "Half day", icon: "bike" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    published: true,
    days: [
      {
        title: "Virupaksha and Hemakuta",
        morning: "Arrive at Hosapete and drive to Hampi. Check in near the bazaar or in Kamalapura.",
        afternoon: "Virupaksha Temple, still in worship, and the old Hampi Bazaar.",
        evening: "Sunset from Hemakuta Hill among its small temples.",
        stay: "Hampi Bazaar area or Kamalapura",
        tip: "Remove footwear at the temple gate. Cover shoulders and knees.",
        stops: [
          { name: "Virupaksha Temple", lat: 15.335, lng: 76.4589 },
          { name: "Hemakuta Hill", lat: 15.3333, lng: 76.4583 },
        ],
      },
      {
        title: "Vittala Temple and the river",
        morning: "Walk or ride to Vittala Temple to see the stone chariot and the carved pillared halls.",
        afternoon: "Walk back along the river past Achyutaraya Temple. Coracle ride on the Tungabhadra.",
        evening: "Sunset from Matanga Hill.",
        stay: "Hampi Bazaar area or Kamalapura",
        tip: "Reach Vittala at opening time to avoid the heat and crowds. Battery cars run from the parking to the temple.",
        stops: [
          { name: "Vittala Temple", lat: 15.342, lng: 76.4747 },
          { name: "Achyutaraya Temple", lat: 15.3363, lng: 76.4683 },
          { name: "Matanga Hill", lat: 15.3382, lng: 76.4633 },
        ],
      },
      {
        title: "The Royal Centre",
        morning: "Lakshmi Narasimha statue and Badavilinga, then Hazara Rama Temple.",
        afternoon: "Royal Enclosure and its stepped tank, the Lotus Mahal, Elephant Stables and Queen's Bath.",
        evening: "Dinner in Kamalapura.",
        stay: "Hampi Bazaar area or Kamalapura",
        tip: "Your Vittala Temple ticket also covers the Zenana Enclosure (Lotus Mahal) and Elephant Stables on the same day. Keep it.",
        stops: [
          { name: "Lakshmi Narasimha", lat: 15.3328, lng: 76.4644 },
          { name: "Royal Enclosure", lat: 15.3175, lng: 76.4706 },
          { name: "Elephant Stables", lat: 15.3232, lng: 76.476 },
        ],
      },
      {
        title: "Anegundi and Anjanadri",
        morning: "Cross the river to Anegundi, older than Hampi, and walk its village lanes.",
        afternoon: "Rest by Sanapur Lake or a paddy-side café.",
        evening: "Climb the 575 steps of Anjanadri Hill, said to be Hanuman's birthplace, for sunset.",
        stay: "Hampi Bazaar area or Kamalapura",
        tip: "River boats stop at dusk and do not run when the river is high. Check the last boat or go round by road.",
        stops: [
          { name: "Anegundi", lat: 15.35, lng: 76.495 },
          { name: "Anjanadri Hill", lat: 15.353, lng: 76.48 },
        ],
      },
      {
        title: "Museum and Tungabhadra Dam",
        morning: "ASI Archaeological Museum at Kamalapura for sculptures and a scale model of the site.",
        afternoon: "Optional evening trip to Daroji Bear Sanctuary to watch sloth bears from the watchtower.",
        evening: "Or visit Tungabhadra Dam and its lit-up gardens near Hosapete.",
        stay: "Hampi Bazaar area or Kamalapura",
        tip: "The Kamalapura museum is usually closed on Fridays.",
        stops: [
          { name: "Kamalapura", lat: 15.3087, lng: 76.4795 },
          { name: "Tungabhadra Dam", lat: 15.2683, lng: 76.3381 },
        ],
      },
      {
        title: "Morning cycle and depart",
        morning: "Rent a bicycle and ride the quiet roads between the ruins at sunrise.",
        afternoon: "Head to Hosapete for your train or onward drive.",
        evening: "Departure.",
        stay: "—",
        tip: "With an extra two days, Badami, Aihole and Pattadakal are about 3.5 hrs away.",
        stops: [{ name: "Hosapete station", lat: 15.2696, lng: 76.3878 }],
      },
    ],
  },
];
