import type { Destination } from "../types";

// Seed content. Loaded into the database by `npm run db:seed`; edited afterwards in the admin panel.

export const west: Destination[] = [
  {
    slug: "jaipur",
    featured: true,
    name: "Jaipur",
    state: "Rajasthan",
    tagline: "The Pink City",
    summary: "Hilltop forts, a royal observatory and busy bazaars inside the old walled Pink City.",
    tourType: "heritage",
    lat: 26.9124,
    lng: 75.7873,
    bestTime: {
      months: "Oct – Mar",
      note: "Pleasant days and cool nights. Apr–Jun is very hot; monsoon (Jul–Sep) is humid but green.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Jaipur (JAI) or take a train to Jaipur Junction. From Delhi it is about 5 hrs by road or 4–5 hrs by train.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹12,000+" },
    facts: [
      { label: "Founded", value: "1727" },
      { label: "Landscape", value: "Aravalli hills" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Amber Fort" },
    ],
    experiences: [
      { name: "Amber Fort walk", duration: "3 hrs", icon: "castle" },
      { name: "Old city bazaars", duration: "2–3 hrs", icon: "shopping" },
      { name: "Nahargarh sunset", duration: "2 hrs", icon: "sunrise" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Arrive and the old city",
        morning: "Arrive and check in. Rest if you came in on an early train or flight.",
        afternoon: "Hawa Mahal, then walk Johari and Bapu Bazaars for block prints, jewellery and mojris.",
        evening: "See Albert Hall lit up after dark, then dinner nearby.",
        stay: "Old city or C-Scheme",
        tip: "Buy the composite ticket; it covers Amber, Hawa Mahal, Jantar Mantar, Albert Hall and Nahargarh over two days.",
        stops: [
          { name: "Hawa Mahal", lat: 26.9239, lng: 75.8267 },
          { name: "Bapu Bazaar", lat: 26.9186, lng: 75.8217 },
          { name: "Albert Hall", lat: 26.9116, lng: 75.8195 },
        ],
      },
      {
        title: "Amber Fort and Jaigarh",
        morning: "Reach Amber Fort when it opens, before the tour buses. Sheesh Mahal and the zenana courtyards.",
        afternoon: "Panna Meena ka Kund stepwell, then Jaigarh Fort and the Jaivana cannon.",
        evening: "Stop at the Jal Mahal viewpoint on the way back to town.",
        stay: "Old city or C-Scheme",
        tip: "Walk or take a jeep up to Amber rather than an elephant ride.",
        stops: [
          { name: "Amber Fort", lat: 26.9855, lng: 75.8513 },
          { name: "Jaigarh Fort", lat: 26.9851, lng: 75.8456 },
          { name: "Jal Mahal", lat: 26.9535, lng: 75.8462 },
        ],
      },
      {
        title: "City Palace and Nahargarh",
        morning: "City Palace museum and courtyards, then Jantar Mantar's giant stone instruments next door.",
        afternoon: "Drive up to Nahargarh Fort and walk the Madhavendra Bhawan rooms.",
        evening: "Sunset over the city from the Nahargarh walls.",
        stay: "Old city or C-Scheme",
        tip: "City Palace is privately run and not on the composite ticket.",
        stops: [
          { name: "City Palace", lat: 26.9258, lng: 75.8237 },
          { name: "Jantar Mantar", lat: 26.9248, lng: 75.8246 },
          { name: "Nahargarh Fort", lat: 26.9373, lng: 75.8155 },
        ],
      },
      {
        title: "Galta Ji and gardens",
        morning: "Galta Ji, the temple complex of spring-fed tanks in a gorge east of the city.",
        afternoon: "Sisodia Rani garden, then Birla Mandir in white marble.",
        evening: "Rajasthani thali and folk shows at Chokhi Dhani on Tonk Road.",
        stay: "Old city or C-Scheme",
        tip: "Galta Ji has many monkeys. Keep food and loose items in your bag.",
        stops: [
          { name: "Galta Ji", lat: 26.9165, lng: 75.8597 },
          { name: "Birla Mandir", lat: 26.8921, lng: 75.8155 },
        ],
      },
      {
        title: "Abhaneri stepwell",
        morning: "Drive about 2 hrs east to Chand Baori, one of India's deepest stepwells.",
        afternoon: "Harshat Mata temple next door, then drive back.",
        evening: "Free evening in the old city.",
        stay: "Old city or C-Scheme",
        tip: "Start early; the stepwell photographs best in soft morning light.",
        stops: [{ name: "Chand Baori, Abhaneri", lat: 27.0074, lng: 76.6067 }],
      },
      {
        title: "Patrika Gate and depart",
        morning: "Patrika Gate at Jawahar Circle for its painted arches.",
        afternoon: "Last shopping for blue pottery and quilts, then head to the airport or station.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Patrika Gate", lat: 26.8418, lng: 75.8013 }],
      },
    ],
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    tagline: "City of Lakes",
    summary: "Palaces on Lake Pichola, sunset boat rides and day trips to Kumbhalgarh and Ranakpur.",
    tourType: "heritage",
    lat: 24.5854,
    lng: 73.7125,
    bestTime: {
      months: "Sep – Mar",
      note: "Lakes are fullest after the monsoon and winters are mild. Apr–Jun is hot.",
    },
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Udaipur (UDR), about 22 km from town, or take a train to Udaipur City. Ahmedabad is about 4–5 hrs by road.",
    budgetPerDay: { budget: "₹1,800–3,000", mid: "₹5,000–9,000", premium: "₹20,000+" },
    facts: [
      { label: "Founded", value: "1559" },
      { label: "Landscape", value: "Lakes and hills" },
      { label: "Best time", value: "Sep–Mar" },
      { label: "Famous for", value: "Lake palaces" },
    ],
    experiences: [
      { name: "Lake Pichola boat ride", duration: "1 hr", icon: "boat" },
      { name: "City Palace museum", duration: "2–3 hrs", icon: "castle" },
      { name: "Dharohar folk dance", duration: "1 hr", icon: "music" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Arrive and the old city",
        morning: "Arrive and check in near Lake Pichola.",
        afternoon: "Jagdish Temple, then walk down to Gangaur Ghat on the lake.",
        evening: "Dharohar folk dance show at Bagore ki Haveli, then dinner on a lakeside rooftop.",
        stay: "Lal Ghat / Gangaur Ghat area",
        tip: "Reach Bagore ki Haveli 30 min early for a good seat at the dance show.",
        stops: [
          { name: "Jagdish Temple", lat: 24.5795, lng: 73.6838 },
          { name: "Bagore ki Haveli", lat: 24.58, lng: 73.682 },
        ],
      },
      {
        title: "City Palace and the lake",
        morning: "City Palace museum: courtyards, mirror work and views over the lake.",
        afternoon: "Boat ride on Lake Pichola, with a stop at Jag Mandir island.",
        evening: "Sunset at Ambrai Ghat facing the palace.",
        stay: "Lal Ghat / Gangaur Ghat area",
        tip: "Take the late-afternoon boat for the best light on the palace.",
        stops: [
          { name: "City Palace", lat: 24.5764, lng: 73.6835 },
          { name: "Jag Mandir", lat: 24.57, lng: 73.682 },
          { name: "Ambrai Ghat", lat: 24.5785, lng: 73.68 },
        ],
      },
      {
        title: "Gardens and the Monsoon Palace",
        morning: "Saheliyon ki Bari, the fountain garden built for royal ladies.",
        afternoon: "Walk or cycle along Fateh Sagar Lake.",
        evening: "Drive up to Sajjangarh (Monsoon Palace) for sunset over the lakes.",
        stay: "Lal Ghat / Gangaur Ghat area",
        tip: "Sajjangarh is inside a wildlife sanctuary; take the shared vehicle from the gate.",
        stops: [
          { name: "Saheliyon ki Bari", lat: 24.6036, lng: 73.6874 },
          { name: "Fateh Sagar Lake", lat: 24.6009, lng: 73.6766 },
          { name: "Sajjangarh", lat: 24.5925, lng: 73.6352 },
        ],
      },
      {
        title: "Kumbhalgarh and Ranakpur",
        morning: "Drive about 2.5 hrs to Kumbhalgarh Fort and walk part of its long walls.",
        afternoon: "Ranakpur Jain temple, famous for its hundreds of carved marble pillars.",
        evening: "Drive back to Udaipur (about 2.5 hrs).",
        stay: "Lal Ghat / Gangaur Ghat area",
        tip: "Ranakpur opens to visitors only from noon. Leather items are not allowed inside.",
        stops: [
          { name: "Kumbhalgarh Fort", lat: 25.1486, lng: 73.585 },
          { name: "Ranakpur Jain Temple", lat: 25.1159, lng: 73.4728 },
        ],
      },
      {
        title: "Chittorgarh Fort",
        morning: "Drive about 2 hrs to Chittorgarh, one of the largest forts in India.",
        afternoon: "Vijay Stambh, Rani Padmini's palace and the Meera temple inside the fort.",
        evening: "Return to Udaipur.",
        stay: "Lal Ghat / Gangaur Ghat area",
        tip: "The fort is spread out over several kilometres; keep your car for the loop.",
        stops: [{ name: "Chittorgarh Fort", lat: 24.887, lng: 74.647 }],
      },
      {
        title: "Eklingji and depart",
        morning: "Eklingji temple and the old Sas-Bahu temples at nearby Nagda.",
        afternoon: "Head to the airport or station.",
        evening: "Departure.",
        stay: "—",
        tip: "Eklingji does not allow phones or cameras inside; there are lockers at the gate.",
        stops: [{ name: "Eklingji", lat: 24.7464, lng: 73.7229 }],
      },
    ],
  },
  {
    slug: "varanasi",
    featured: true,
    name: "Varanasi",
    state: "Uttar Pradesh",
    tagline: "City of the Ganga",
    summary: "Dawn boat rides past the ghats, the evening Ganga Aarti and the Buddhist site of Sarnath.",
    tourType: "heritage",
    lat: 25.3176,
    lng: 82.9739,
    bestTime: {
      months: "Oct – Mar",
      note: "Cool, clear mornings for boat rides. Summers are very hot, and in monsoon the river rises over the lower ghats.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Fly to Varanasi (VNS), about 25 km from the ghats, or take a train to Varanasi Junction or Banaras station. Vande Bharat runs from Delhi.",
    budgetPerDay: { budget: "₹1,200–2,000", mid: "₹3,500–6,000", premium: "₹10,000+" },
    facts: [
      { label: "River", value: "Ganga" },
      { label: "Ghats", value: "80+" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Ganga Aarti" },
    ],
    experiences: [
      { name: "Sunrise boat ride", duration: "1.5 hrs", icon: "boat" },
      { name: "Ganga Aarti", duration: "1 hr", icon: "temple" },
      { name: "Street food walk", duration: "2 hrs", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Arrive and the evening Aarti",
        morning: "Arrive and check in near the ghats.",
        afternoon: "Walk the riverfront between ghats to get your bearings.",
        evening: "Ganga Aarti at Dashashwamedh Ghat.",
        stay: "Near the ghats",
        tip: "Arrive 45 min early, or watch from a boat on the river for a clear view.",
        stops: [{ name: "Dashashwamedh Ghat", lat: 25.307, lng: 83.0104 }],
      },
      {
        title: "Dawn on the river and Kashi Vishwanath",
        morning: "Sunrise boat ride from Assi Ghat downriver to Manikarnika.",
        afternoon: "Kashi Vishwanath temple, then explore the old lanes around it.",
        evening: "Food walk: kachori-sabzi, lassi and, in winter, malaiyo.",
        stay: "Near the ghats",
        tip: "Phones and bags are not allowed in Kashi Vishwanath; use the lockers. Agree the boat fare before you get in.",
        stops: [
          { name: "Assi Ghat", lat: 25.2899, lng: 83.0067 },
          { name: "Manikarnika Ghat", lat: 25.3105, lng: 83.014 },
          { name: "Kashi Vishwanath", lat: 25.3109, lng: 83.0107 },
        ],
      },
      {
        title: "Sarnath",
        morning: "Drive 30 min to Sarnath, where the Buddha gave his first sermon. Dhamek Stupa and the ruins.",
        afternoon: "Sarnath museum, home of the Ashoka lion capital, and the Thai and Tibetan temples.",
        evening: "Quieter evening at Assi Ghat.",
        stay: "Near the ghats",
        tip: "The Sarnath museum is closed on Fridays.",
        stops: [{ name: "Dhamek Stupa, Sarnath", lat: 25.3808, lng: 83.0244 }],
      },
      {
        title: "BHU and Ramnagar",
        morning: "Banaras Hindu University campus and the Bharat Kala Bhavan museum.",
        afternoon: "Sankat Mochan temple, then cross the river to Ramnagar Fort.",
        evening: "Boat back along the ghats at dusk.",
        stay: "Near the ghats",
        stops: [
          { name: "Bharat Kala Bhavan, BHU", lat: 25.2677, lng: 82.9913 },
          { name: "Sankat Mochan", lat: 25.2815, lng: 82.9998 },
          { name: "Ramnagar Fort", lat: 25.2845, lng: 83.0267 },
        ],
      },
      {
        title: "Chunar Fort",
        morning: "Drive about 1 hr to Chunar Fort on a rock above the Ganga.",
        afternoon: "Explore the fort and its river views, then return.",
        evening: "Free evening on the ghats.",
        stay: "Near the ghats",
        stops: [{ name: "Chunar Fort", lat: 25.1262, lng: 82.874 }],
      },
      {
        title: "Silk weavers and depart",
        morning: "Subah-e-Banaras music and aarti at Assi Ghat at dawn.",
        afternoon: "See Banarasi silk being woven on handlooms, then head to the airport or station.",
        evening: "Departure.",
        stay: "—",
        tip: "Buy silk from a weaver or a government emporium rather than a shop your guide steers you to.",
        stops: [{ name: "Assi Ghat", lat: 25.2899, lng: 83.0067 }],
      },
    ],
  },
  {
    slug: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    tagline: "Home of the Taj",
    summary: "The Taj Mahal at sunrise, Agra Fort and Fatehpur Sikri, with Mathura and Vrindavan close by.",
    tourType: "heritage",
    lat: 27.1767,
    lng: 78.0081,
    bestTime: {
      months: "Oct – Mar",
      note: "Pleasant days, though Dec–Jan mornings can be foggy. Apr–Jun is very hot.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3],
    howToReach:
      "Trains from Delhi reach Agra Cantt in about 2 hrs. By road it is 3–4 hrs on the Yamuna Expressway.",
    budgetPerDay: { budget: "₹1,500–2,500", mid: "₹4,000–7,000", premium: "₹15,000+" },
    facts: [
      { label: "UNESCO sites", value: "3" },
      { label: "Taj closed", value: "Fridays" },
      { label: "Best time", value: "Oct–Mar" },
      { label: "Famous for", value: "Taj Mahal" },
    ],
    experiences: [
      { name: "Taj Mahal at sunrise", duration: "3 hrs", icon: "sunrise" },
      { name: "Agra Fort", duration: "2 hrs", icon: "castle" },
      { name: "Petha and chaat trail", duration: "2 hrs", icon: "food" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Agra Fort and Mehtab Bagh",
        morning: "Arrive and check in near the Taj.",
        afternoon: "Agra Fort: Diwan-i-Aam, Diwan-i-Khas and the view of the Taj from Musamman Burj.",
        evening: "Sunset view of the Taj from Mehtab Bagh across the Yamuna.",
        stay: "Near the Taj (Taj Ganj / Fatehabad Road)",
        tip: "If you arrive on a Friday, do this day first; the Taj is closed on Fridays.",
        stops: [
          { name: "Agra Fort", lat: 27.1795, lng: 78.0211 },
          { name: "Mehtab Bagh", lat: 27.1795, lng: 78.0444 },
        ],
      },
      {
        title: "Taj Mahal at sunrise",
        morning: "Enter the Taj Mahal at opening, just before sunrise, when it is coolest and least crowded.",
        afternoon: "Itmad-ud-Daulah, the 'Baby Taj', with fine inlay work.",
        evening: "Kinari Bazaar near Jama Masjid for petha and chaat.",
        stay: "Near the Taj (Taj Ganj / Fatehabad Road)",
        tip: "Book tickets online. Food, tripods and large bags are not allowed inside the Taj.",
        stops: [
          { name: "Taj Mahal", lat: 27.1751, lng: 78.0421 },
          { name: "Itmad-ud-Daulah", lat: 27.1929, lng: 78.0311 },
          { name: "Jama Masjid, Agra", lat: 27.1833, lng: 78.0157 },
        ],
      },
      {
        title: "Fatehpur Sikri",
        morning: "Drive about 1 hr to Fatehpur Sikri, Akbar's short-lived red sandstone capital.",
        afternoon: "Buland Darwaza and the tomb of Salim Chishti, then back to Agra.",
        evening: "Free evening.",
        stay: "Near the Taj (Taj Ganj / Fatehabad Road)",
        tip: "Use an approved guide from the ticket counter and ignore touts at the gate.",
        stops: [{ name: "Fatehpur Sikri", lat: 27.0945, lng: 77.6679 }],
      },
      {
        title: "Sikandra and Mathura",
        morning: "Akbar's Tomb at Sikandra, on the road north.",
        afternoon: "Drive on to Mathura and visit the Shri Krishna Janmabhoomi temple.",
        evening: "Aarti at Vishram Ghat on the Yamuna.",
        stay: "Mathura or Vrindavan",
        tip: "Phones are not allowed inside Janmabhoomi; carry as little as possible.",
        stops: [
          { name: "Akbar's Tomb, Sikandra", lat: 27.2206, lng: 77.9506 },
          { name: "Krishna Janmabhoomi", lat: 27.5047, lng: 77.6697 },
        ],
      },
      {
        title: "Vrindavan",
        morning: "Banke Bihari temple in the old lanes of Vrindavan.",
        afternoon: "ISKCON temple and a walk along the ghats.",
        evening: "Prem Mandir when its lights come on after dark.",
        stay: "Mathura or Vrindavan",
        tip: "Banke Bihari closes in the afternoon; check darshan timings before you go. Watch out for monkeys snatching glasses.",
        stops: [
          { name: "Banke Bihari Temple", lat: 27.5813, lng: 77.6966 },
          { name: "Prem Mandir", lat: 27.5716, lng: 77.672 },
        ],
      },
      {
        title: "Govardhan and depart",
        morning: "Govardhan, the hill tied to the Krishna legends; walk a short stretch of the parikrama path.",
        afternoon: "Head to Mathura Junction for trains, or back to Agra or Delhi.",
        evening: "Departure.",
        stay: "—",
        tip: "Mathura Junction has frequent trains to Delhi, Agra and Mumbai.",
        stops: [{ name: "Govardhan", lat: 27.4974, lng: 77.463 }],
      },
    ],
  },
  {
    slug: "rann-of-kutch",
    name: "Rann of Kutch",
    state: "Gujarat",
    tagline: "The White Desert",
    summary: "A vast white salt desert, craft villages and full-moon nights, with Bhuj as the base.",
    tourType: "desert",
    lat: 23.242,
    lng: 69.6669,
    bestTime: {
      months: "Nov – Mar",
      note: "The salt is dry and white and Rann Utsav runs in winter. In monsoon the Rann floods.",
    },
    bestMonths: [11, 12, 1, 2, 3],
    howToReach:
      "Fly to Bhuj (BHJ) from Mumbai, or take a train to Bhuj from Mumbai or Ahmedabad. Ahmedabad is about 6 hrs by road. Dhordo is 85 km north of Bhuj.",
    budgetPerDay: { budget: "₹2,000–3,000", mid: "₹5,000–9,000", premium: "₹15,000+" },
    facts: [
      { label: "Landscape", value: "Salt desert" },
      { label: "Base", value: "Bhuj" },
      { label: "Permit", value: "Needed" },
      { label: "Best time", value: "Nov–Mar" },
    ],
    experiences: [
      { name: "White Rann at sunset", duration: "2–3 hrs", icon: "sunrise" },
      { name: "Craft village visits", duration: "Half day", icon: "shopping" },
      { name: "Tent or bhunga stay", duration: "Overnight", icon: "tent" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Arrive in Bhuj",
        morning: "Arrive in Bhuj and check in.",
        afternoon: "Aina Mahal and Prag Mahal in the old palace quarter, then the Kutch Museum.",
        evening: "Walk around Hamirsar Lake.",
        stay: "Bhuj",
        tip: "Draw cash in Bhuj; ATMs are scarce once you head north towards the Rann.",
        stops: [
          { name: "Aina Mahal", lat: 23.254, lng: 69.668 },
          { name: "Kutch Museum", lat: 23.25, lng: 69.672 },
        ],
      },
      {
        title: "The White Rann",
        morning: "Drive about 2 hrs north towards Dhordo. Stop at Hodka or Bhirandiyara for crafts and mawa sweets.",
        afternoon: "Check in at a tent or bhunga stay near Dhordo.",
        evening: "Sunset on the White Rann from the Dhordo watchtower area.",
        stay: "Dhordo (tent or bhunga)",
        tip: "You need a permit for the White Rann. Get it online or at the Bhirandiyara checkpost and carry original ID.",
        stops: [
          { name: "Dhordo", lat: 23.8195, lng: 69.654 },
          { name: "White Rann", lat: 23.85, lng: 69.65 },
        ],
      },
      {
        title: "Kala Dungar and back to Bhuj",
        morning: "Go back to the White Rann at sunrise, or on a full-moon night the evening before.",
        afternoon: "Kala Dungar, the highest point in Kutch, for views over the Rann. Pottery at Khavda.",
        evening: "Drive back to Bhuj.",
        stay: "Bhuj",
        stops: [
          { name: "Kala Dungar", lat: 23.8833, lng: 69.8297 },
          { name: "Khavda", lat: 23.85, lng: 69.73 },
        ],
      },
      {
        title: "Mandvi",
        morning: "Drive 1 hr to Mandvi. Vijay Vilas Palace, the old summer palace by the sea.",
        afternoon: "Watch wooden dhows being built by hand at the shipyard on the river.",
        evening: "Sunset on Mandvi beach, with dabeli in town.",
        stay: "Mandvi",
        stops: [
          { name: "Vijay Vilas Palace", lat: 22.824, lng: 69.329 },
          { name: "Mandvi beach", lat: 22.825, lng: 69.356 },
        ],
      },
      {
        title: "Lakhpat and Nirona",
        morning: "Long drive west to Lakhpat Fort, an old port town on the creek, with a stop at Mata no Madh.",
        afternoon: "Nirona village on the way back for rogan art and bell-making.",
        evening: "Return to Bhuj.",
        stay: "Bhuj",
        tip: "This is a full day with about 6 hrs of driving. Carry water and snacks.",
        stops: [
          { name: "Lakhpat Fort", lat: 23.824, lng: 68.776 },
          { name: "Mata no Madh", lat: 23.533, lng: 68.945 },
          { name: "Nirona", lat: 23.467, lng: 69.441 },
        ],
      },
      {
        title: "Bhujodi and depart",
        morning: "Bhujodi weaving village, just outside Bhuj, for shawls and textiles.",
        afternoon: "Head to Bhuj airport or station.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Bhujodi", lat: 23.221, lng: 69.713 }],
      },
    ],
  },
  {
    slug: "ranthambore",
    name: "Ranthambore",
    state: "Rajasthan",
    tagline: "Tigers among ruins",
    summary: "Jeep safaris for wild tigers, with a 10th-century fort rising out of the jungle.",
    tourType: "wildlife",
    lat: 26.0173,
    lng: 76.5026,
    bestTime: {
      months: "Oct – Jun",
      note: "Oct–Mar is pleasant. Apr–Jun is hot but tigers are easier to spot near water. Core zones close Jul–Sep for monsoon.",
    },
    bestMonths: [10, 11, 12, 1, 2, 3, 4, 5, 6],
    howToReach:
      "Take a train to Sawai Madhopur, on the Delhi–Mumbai line. Jaipur airport is about 3.5 hrs by road. Park gates are 10–15 km from town.",
    budgetPerDay: { budget: "₹2,500–4,000", mid: "₹7,000–12,000", premium: "₹25,000+" },
    facts: [
      { label: "Safari zones", value: "10" },
      { label: "Open", value: "Oct–Jun" },
      { label: "Landscape", value: "Dry forest" },
      { label: "Famous for", value: "Tigers" },
    ],
    experiences: [
      { name: "Jeep (gypsy) safari", duration: "3–3.5 hrs", icon: "binoculars" },
      { name: "Ranthambore Fort", duration: "2–3 hrs", icon: "castle" },
      { name: "Wildlife photography", duration: "Half day", icon: "camera" },
    ],
    minDays: 2,
    lastChecked: "2026-09-28",
    days: [
      {
        title: "Arrive and first safari",
        morning: "Arrive in Sawai Madhopur and check in along Ranthambore Road.",
        afternoon: "First afternoon safari, if you have booked one.",
        evening: "Early dinner and an early night; morning safaris start at dawn.",
        stay: "Ranthambore Road",
        tip: "Book safaris on the Rajasthan forest department's official portal as soon as bookings open. Gypsies seat 6 and are better than 20-seat canters.",
        stops: [{ name: "Ranthambore National Park", lat: 26.0173, lng: 76.5026 }],
      },
      {
        title: "Morning safari and the fort",
        morning: "Dawn safari, the best time for tiger movement.",
        afternoon: "Ranthambore Fort and the Trinetra Ganesh temple inside it.",
        evening: "Rest at your stay.",
        stay: "Ranthambore Road",
        tip: "Carry the ID you used to book; it is checked at the gate. Wear earth tones and a warm layer in winter.",
        stops: [{ name: "Ranthambore Fort", lat: 26.0167, lng: 76.4556 }],
      },
      {
        title: "Second zone",
        morning: "Safari in a different zone; each covers different lakes and terrain.",
        afternoon: "Rest through the heat of the day.",
        evening: "Afternoon safari if you want more chances.",
        stay: "Ranthambore Road",
        tip: "Zones are allotted at booking; you cannot switch on the day.",
        stops: [{ name: "Ranthambore National Park", lat: 26.0173, lng: 76.5026 }],
      },
      {
        title: "Birds and crafts",
        morning: "Birding at Surwal Lake, a seasonal wetland outside town (best Nov–Feb).",
        afternoon: "Visit a local craft cooperative for block prints and textiles.",
        evening: "Quiet evening at your stay.",
        stay: "Ranthambore Road",
        stops: [{ name: "Surwal Lake", lat: 26.08, lng: 76.38 }],
      },
      {
        title: "Last safari",
        morning: "Dawn safari for another chance at tigers, leopards and sloth bears.",
        afternoon: "Rest, or sort photos from the week.",
        evening: "Afternoon safari, or a slow evening if you have seen enough.",
        stay: "Ranthambore Road",
        stops: [{ name: "Ranthambore National Park", lat: 26.0173, lng: 76.5026 }],
      },
      {
        title: "Sawai Madhopur and depart",
        morning: "Look at the wildlife murals at Sawai Madhopur station while you wait for your train.",
        afternoon: "Train or drive to Jaipur, Delhi or Mumbai.",
        evening: "Departure.",
        stay: "—",
        stops: [{ name: "Sawai Madhopur station", lat: 25.9952, lng: 76.3533 }],
      },
    ],
  },
];
